(function(g){var window=this;'use strict';var gx=function(b){b.isActive()||b.start()},XX=function(b){var W={languageCode:b.languageCode,
languageName:b.languageName,displayName:g.oM(b),kind:b.kind,name:b.name,id:b.id,is_servable:b.Z,is_default:b.isDefault,is_translateable:b.isTranslateable,vss_id:b.vssId};b.xtags&&(W.xtags=b.xtags);b.captionId&&(W.captionId=b.captionId);b.translationLanguage&&(W.translationLanguage=b.translationLanguage);return W},nCw=function(b,W){var c=new g.pk;
c.languageCode=b.languageCode;c.languageName=b.languageName;c.name=b.name;c.displayName=b.displayName;c.kind=b.kind;c.isDefault=!1;c.Z=b.Z;c.isTranslateable=b.isTranslateable;c.vssId=b.vssId;c.url=b.url;c.translationLanguage=W;b.xtags&&(c.xtags=b.xtags);b.captionId&&(c.captionId=b.captionId);return c},t8=function(b,W){return W?b.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},HpY=function(b){return g.q_(b)||b.j("web_enable_caption_language_preference_stickiness")},dw2=async function(b,W){b=
b+"|"+W;
W=await g.uN();if(!W)throw g.An("gct");return(await g.aA(W)).get("captions",b)},Cg2=function(b,W,c){dw2(b,W).then(U=>{U&&c(U.trackData,new g.pk(U.metadata))})},xZ=function(b){if(!r4b.test(b))throw Error("'"+b+"' is not a valid hex color");
b.length==4&&(b=b.replace(ptb,"#$1$1$2$2$3$3"));b=b.toLowerCase();b=parseInt(b.slice(1),16);return[b>>16,b>>8&255,b&255]},zhY=function(){var b={},W="suggest_correction"in g.g2?g.g2.suggest_correction:"Edit caption";
W=W||"";for(let c in b){let U=()=>String(b[c]);
W=W.replace(new RegExp("\\$\\{"+c+"\\}","gi"),U);W=W.replace(new RegExp("\\$"+c,"gi"),U)}return W},A8=function(){return g.BQ("yt-player-caption-display-settings")},oCb=function(b,W){g.kU(W,c=>b.equals(c))||W.push(b)},v3=function(b,W){switch(W.kind){case "asr":oCb(W,b.O);
break;default:oCb(W,b.X)}},bdy=async function(b){if(b.A)try{await b.A.promise}catch{}},Wiv=async function(b,W,c){b.X=g.gU(W,c)},cDw=async function(b,W,c,U){try{let u=b.N;
if(b.uX.S().j("html5_await_track_decoration_in_load_track")&&(await bdy(b),b.I1()||b.N!==u))return;let I=b.L(W,c),D=b.uX.S().j("html5_report_captions_ctmp_qoe"),h=(0,g.n)();await Wiv(b,I,{format:"RAW",onSuccess:K=>{if(b.X){b.X=null;if(D){var m=(K.responseText.length/1024).toFixed();let F=(0,g.n)();b.videoData.W("capresp",{ms:F-h,kb:m})}m=K.getResponseHeader&&K.getResponseHeader("Content-Length")?Number(K.getResponseHeader("Content-Length")):0;U.CL(K.responseText,W,void 0,void 0,m)}},
onError:D?K=>{b.videoData.W("capfail",{status:K?.status??0})}:void 0,
withCredentials:!0})}catch{}},id2=function(b,W){var c=g.Wy(b.segments,W);
c>=0||c<0&&(-c-1)%2===1||(c=-c-1,c>0&&W-b.segments[c-1]===1&&c<b.segments.length&&b.segments[c]-W===1?(g.nG(b.segments,c),g.nG(b.segments,c-1)):c>0&&W-b.segments[c-1]===1?b.segments[c-1]=W:c<b.segments.length&&b.segments[c]-W===1?b.segments[c]=W:(g.zK(b.segments,c,0,W),g.zK(b.segments,c+1,0,W)))},Uxy=function(b){return b.Z&&b.Z.Y?b.Z.Y+b.player.NH()<b.player.getCurrentTime():!1},uq2=function(b,W){if(b.policy.uH&&b.player.I7()){var c=g.Bm(W,b.policy,{});
c.set("pot",b.player.I7());c=c.jV()}else c=g.Bm(W,b.policy,{}).jV();var U={format:"RAW",withCredentials:!0};if(b.policy.yj){U.method="POST";let D=W.A;D&&Object.keys(D).length>0?U.postBody=g.L9(D,g.IM):U.postBody=(0,g.W9)([120,0])}b.Y&&(U.responseType="arraybuffer");var u=++b.O0,I=(0,g.n)();b.X=g.f3(c,U,3,100,-1,D=>{D.errorCode==="net.timeout"&&b.player.W("capnt",{rn:u++})}).then(D=>{if(b.policy.VM&&u%100===1){var h=(0,g.n)();
b.player.W("caprsp",{rn:u,ms:h-I,kb:(D.xhr.responseText.length/1024).toFixed()})}a:{D=D.xhr;b.I1();if(b.O){var K=!(b.Y?D.response:D.responseText)||D.status>=400;if(h=g.Pq(D)){D=g.Bm(b.O,b.policy,{});b.O.Cv(D,h);uq2(b,b.O);break a}K?b.player.W("capfail",{status:D.status}):(g.Km("fcb_r",(0,g.n)(),b.player.getVideoData().qI||""),h=b.O.K9[0],K=h.Yv,b.N!=null&&b.L!==K&&(b.Y?b.N(D.response,(h.segmentStartTime+b.player.NH())*1E3):b.N(D.responseText,(h.segmentStartTime+b.player.NH())*1E3),b.L=K))}b.O=null;
b.X=null}}).im(D=>{b.O=null;
b.X=null;b.player.W("capfail",{rn:u,status:D.xhr?.status})});
b.O=W;id2(b.A,b.O.K9[0].Yv)},shv=function(b,W){return W!=null&&W in b.X.Z?b.X.Z[W]:null},IZ1=function(b,W,c){var U=[];
for(let u in b.X.Z){if(!b.X.Z.hasOwnProperty(u))continue;let I=b.X.Z[u];if(g.wh(I,c||null)){let D=I.info.captionTrack;D&&D.languageCode===W&&U.push(I)}}return U.length?U[0]:null},DxD=function(b,W){var c=[];
for(let u in b.X.Z){if(!b.X.Z.hasOwnProperty(u))continue;var U=b.X.Z[u];if(g.wh(U,W||null)){let I=U.info.id,D=I,h=`.${I}`,K="",m="";if(U=U.info.captionTrack)I=U.languageCode,D=U.displayName,h=U.vssId,K=U.kind,m=U.id;c.push(new g.pk({id:u,languageCode:I,languageName:D,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:h,kind:K,captionId:m}))}}return c},Rs=function(b){if(typeof DOMParser!="undefined")return g.Kv(new DOMParser,g.Qp(b),"application/xml");
throw Error("Your browser does not support loading xml documents");},hMR=function(b,W,c,U){var u=W/360*16;
W>=b&&(b=640,U>c*1.3&&(b=480),u=c/b*16);return u},Kiy=function(b){var W=1+.25*(b.fontSizeIncrement||0);
if(b.offset===0||b.offset===2)W*=.8;return W},ZdZ=function(b,W){var c="vertical-rl";
b.Z.q8===1&&(c="vertical-lr");g.hz&&(c=c==="vertical-lr"?"tb-lr":"tb-rl");g.KK(W,"-o-writing-mode",c);g.KK(W,"-webkit-writing-mode",c);g.KK(W,"writing-mode",c);g.KK(W,"text-orientation","upright");g.EB(W,"ytp-vertical-caption");b.O.params.nj===3&&(g.KK(W,"text-orientation",""),g.KK(W,"transform","rotate(180deg)"))},PUY=function(b,W){var c={},U=W.background?W.background:b.Z.Ha.background;
if(W.backgroundOpacity!=null||W.background){var u=W.backgroundOpacity!=null?W.backgroundOpacity:b.Z.Ha.backgroundOpacity;U=xZ(U);c.background="rgba("+U[0]+","+U[1]+","+U[2]+","+u+")";b.Wk&&(c["box-decoration-break"]="clone",c["border-radius"]=`${b.nu*.25}px`)}if(W.fontSizeIncrement!=null||W.offset!=null)c["font-size"]=`${b.vk*Kiy(W)}px`;b.experiments.Sp("enable_player_captions_new_style_defaults")&&(c["line-height"]="1.375");U=1;u=W.color||b.Z.Ha.color;if(W.color||W.textOpacity!=null)u=xZ(u),U=W.textOpacity==
null?b.Z.Ha.textOpacity:W.textOpacity,u="rgba("+u[0]+","+u[1]+","+u[2]+","+U+")",c.color=u,c.fill=u;var I=W.charEdgeStyle;I===0&&(I=void 0);if(I){u=`rgba(34, 34, 34, ${U})`;let K=`rgba(204, 204, 204, ${U})`;W.O9&&(K=u=W.O9);let m=b.vk/16/2,F=Math.max(m,1);var D=Math.max(2*m,1),h=Math.max(3*m,1);let M=Math.max(5*m,1);U=[];switch(I){case 4:for(;h<=M;h+=m)U.push(`${D}px ${D}px ${h}px ${u}`);break;case 1:D=window.devicePixelRatio>=2?.5:1;for(I=F;I<=h;I+=D)U.push(`${I}px ${I}px ${u}`);break;case 2:U.push(`${F}px ${F}px ${K}`);
U.push(`-${F}px -${F}px ${u}`);break;case 3:for(h=0;h<5;h++)U.push(`0 0 ${D}px ${u}`)}c["text-shadow"]=U.join(", ")}u="";switch(W.fontFamily){case 1:u='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", serif-monospace, monospace';break;case 2:u='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:u='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", sans-serif-monospace, monospace';break;case 5:u='"Comic Sans MS", Impact, Handlee, fantasy';break;
case 6:u='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:u=g.n3()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:u='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}u&&(c["font-family"]=u);u=W.offset;u==null&&(u=b.Z.Ha.offset);switch(u){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}W.fontFamily===7&&(c["font-variant"]=
"small-caps");W.bold&&(c["font-weight"]="bold");W.italic&&(c["font-style"]="italic");W.underline&&(c["text-decoration"]="underline");W.Qs&&(c.visibility="hidden");W.Un===1&&b.L&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",u=g.wy||g.Xb,b.O.params.nj===3?c.transform=u?"rotate(90deg)":"rotate(180deg)":u&&(c.transform="rotate(-90deg)"));if(W.textEmphasis===1||W.textEmphasis===2||W.textEmphasis===3||W.textEmphasis===4||W.textEmphasis===5)if(g.wy)c["font-weight"]="bold";else switch(c["text-emphasis-style"]=
"filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",W.textEmphasis){case 4:case 3:c["text-emphasis-position"]="under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Ybb=function(b,W){if(b.mx&&W.length===0)return 0;
b=1;for(let c=0;c<W.length;c++){let U=W[c];typeof U.text==="string"&&(b+=U.text.split("\n").length-1,U.append||c===0||b++)}return b},qS=function(b){b=b.split("px");
return b.length>0?(b=Number(b[0]))?b:0:0},MMZ=function(b,W,c){b.E0=b.E0||!!c;
var U={};Object.assign(U,b.Z.Ha);Object.assign(U,c||W.Z);Object.assign(U,b.bW.Ha);b.zn&&(U.backgroundOpacity=0);(c=!b.J)&&mxy(b);var u=b.bX&&b.Vj&&g.Xa(U,b.Vj)?b.bX:Fiy(b,U),I=typeof W.text==="string",D=I?W.text.split("\n"):[W.text];for(let K=0;K<D.length;K++){var h=K>0||!W.append;let m=D[K];h&&!c?(mxy(b),u=Fiy(b,U)):h&&c&&(c=!1);m&&(u.appendChild(I?g.rs(m):m),I||m.tagName!=="RUBY"||m.childElementCount!==4||g.wy||!g.m0(m.children[2],"text-emphasis")||(h=b.L?"padding-right":"padding-top",g.m0(m.children[2],
"text-emphasis-position")&&(h=b.L?"padding-left":"padding-bottom"),g.TV?g.KK(u,h,"1em"):g.KK(u,h,"0.5em")))}b.Vj=U;b.bX=u;b.U.push(W)},mxy=function(b){if(b.J){var W=b.J;
if(b.Wk){var c=b.Z.textAlign;c===0?(W=W.firstElementChild)&&g.KK(W,{"border-bottom-left-radius":"0"}):c===1&&(W=W.lastElementChild)&&g.KK(W,{"border-bottom-right-radius":"0"})}}b.J=g.Cc("SPAN");g.KK(b.J,{display:"block"});g.EB(b.J,"caption-visual-line");b.Y.appendChild(b.J)},Fiy=function(b,W){var c=g.Cc("SPAN");
g.KK(c,{display:"inline-block","white-space":"pre-wrap"});g.KK(c,PUY(b,W));c.classList.add("ytp-caption-segment");b.J.appendChild(c);b.Wk&&b.Y.children.length>1&&(b=b.Z.textAlign,b===0?c.previousElementSibling||g.KK(c,{"border-top-left-radius":"0"}):b===1&&g.KK(c,{"border-top-right-radius":"0"}));c.previousElementSibling&&(g.KK(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.KK(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},
Xey=function(b,W,c){if(b===255&&W===255||!b&&!W)return{fh:b,
xE:W,result:0};b=gBZ[b];W=gBZ[W];if(b&128){var U;if(U=!(W&128))U=W,U=c.wR()&&c.xE===U;if(U)return{fh:b,xE:W,result:1}}else if(W&128&&1<=b&&b<=31)return{fh:b,xE:W,result:2};return{fh:b,xE:W,result:3}},xxy=function(b,W,c,U){W===255&&c===255||!W&&!c?(++b.O===45&&b.reset(),b.A.X.clear(),b.Y.X.clear()):(b.O=0,tMd(b.A,W,c,U))},AD$=function(b,W){b.Z.sort((c,U)=>{var u=c.time-U.time;
return u===0?c.order-U.order:u});
for(let c of b.Z)b.time=c.time,c.type===0?xxy(b,c.GX,c.rS,W):c.type===1&&b.X&496&&tMd(b.Y,c.GX,c.rS,W);b.Z.length=0},aZ2=function(b,W){switch(b){case 0:return vBb[(W&127)-32];
case 1:return RM1[W&15];case 2:return qb$[W&31];case 3:return $xd[W&31]}return 0},$Z=function(b,W){if(b.style.type===3){var c=0,U=0,u=b.Y.time+0,I="",D="",h=u;
for(var K=1;K<=15;++K){var m=!1;for(var F=U?U:1;F<=32;++F){var M=b.O[K][F];if(M.Z!==0){c===0&&(c=K,U=F);m=String.fromCharCode(M.Z);var t=M.timestamp;t<u&&(u=t);M.timestamp=h;D&&(I+=D,D="");I+=m;m=!0}if((M.Z===0||F===32)&&m){D="\n";break}else if(U&&!m)break}if(c&&!m)break}I&&W.A(c,U,u,h,I)}else for(U=c=0,I=u=b.Y.time+0,D=1;D<=15;++D)for(h="",K=1;K<=32;++K)if(F=b.O[D][K],M=F.Z,M!==0&&(c===0&&(c=D,U=K),m=String.fromCharCode(M),t=F.timestamp,t<=u&&(u=t),h+=m,F.reset()),K===32||M===0)h&&W.A(c,U,u,I,h),
u=I,h="",U=c=0},as=function(b){return b.O[b.row][b.X]},fX=function(b,W,c){W>=2&&b.X>1&&(--b.X,as(b).Z=0);
var U=as(b);U.timestamp=b.Y.time+0;U.Z=aZ2(W,c);b.X<32&&b.X++},fZ1=function(b,W,c,U){for(let D=0;D<U;D++)for(let h=0;h<=32;h++){var u=b.O[W+D][h],I=b.O[c+D][h];
u.Z=I.Z;u.timestamp=I.timestamp}},O6=function(b,W,c){for(let U=0;U<c;U++)for(let u=0;u<=32;u++)b.O[W+U][u].reset()},QM=function(b){b.row=b.Z>0?b.Z:1;
b.X=1;O6(b,0,15)},OdC=function(b){b.style.set(1);
b.Z=b.A;b.Z.Z=0;b.Z.style=b.style;b.O.mode=1<<b.Z.A},yM=function(b,W,c){var U=b.X,u=!1;
switch(b.style.get()){case 4:case 1:case 2:b.style.get()===4&&U.Z>0||($Z(U,c),QM(b.X),QM(b.A),U.row=15,U.Z=W,u=!0)}b.style.set(3);b.Z=U;b.Z.style=b.style;b.O.mode=1<<U.A;u?U.X=1:U.Z!==W&&(U.Z>W?($Z(U,c),O6(U,U.row-U.Z,W)):U.row<W&&(W=U.Z),U.Z=W)},Qhw=function(b){b.style.set(4);
b.Z=b.text;b.Z.style=b.style;b.O.mode=1<<b.Z.A},tMd=function(b,W,c,U){b.X.update();
W=Xey(W,c,b.X);switch(W.result){case 0:return;case 1:case 2:return}var u=W.fh;W=W.xE;if(32<=u||!u)b.Z.mode&b.Z.X&&(c=u,c&128&&(c=127),W&128&&(W=127),b=b.A.Z,c&96&&fX(b,0,c),W&96&&fX(b,0,W),c!==0&&W!==0&&b.style.type===3&&$Z(b,U));else if(u&16)a:if(!b.X.matches(u,W)&&(c=b.X,c.fh=u,c.xE=W,c.state=2,c=u&8?b.L:b.O,b.A=c,b.Z.mode=1<<(b.Y<<2)+(c.Y<<1)+(c.style.type===4?1:0),(b.Z.mode|1<<(b.Y<<2)+(c.Y<<1)+(c.style.type!==4?1:0))&b.Z.X))if(W&64){U=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(u&7)<<1|W>>5&1];
b=W&16?((W&14)>>1)*4:0;W=c.Z;switch(c.style.get()){case 4:U=W.row;break;case 3:if(U!==W.row){if(U<W.Z&&(U=W.Z,U===W.row))break;var I=1+W.row-W.Z;let D=1+U-W.Z;fZ1(W,D,I,W.Z);c=I;u=W.Z;D<I?(I=D+u-I,I>0&&(c+=I,u-=I)):(I=I+u-D,I>0&&(u-=I));O6(W,c,u)}}W.row=U;W.X=b+1}else switch(u&7){case 1:switch(W&112){case 32:fX(c.Z,0,32);break a;case 48:W===57?(U=c.Z,as(U).Z=0,U.X<32&&U.X++):fX(c.Z,1,W&15)}break;case 2:W&32&&fX(c.Z,2,W&31);break;case 3:W&32&&fX(c.Z,3,W&31);break;case 4:case 5:if(32<=W&&W<=47)switch(W){case 32:OdC(c);
break;case 33:U=c.Z;U.X>1&&(--U.X,as(U).Z=0);break;case 36:U=c.Z;b=as(U);for(W=0;W<=15;W++)for(c=0;c<=32;c++)if(U.O[W][c]===b){for(;c<=32;c++)U.O[W][c].reset();break}break;case 37:yM(c,2,U);break;case 38:yM(c,3,U);break;case 39:yM(c,4,U);break;case 40:fX(c.Z,0,32);break;case 41:U=c;U.style.set(2);U.Z=U.X;U.Z.Z=0;U.Z.style=U.style;U.O.mode=1<<U.Z.A;break;case 42:U=c;b=U.text;b.Z=15;b.style.set(4);QM(b);Qhw(U);break;case 43:Qhw(c);break;case 44:b=c;W=b.X;switch(b.style.get()){case 1:case 2:case 3:$Z(W,
U)}O6(W,0,15);break;case 45:b:{W=c;b=W.Z;switch(W.style.get()){default:case 2:case 1:break b;case 4:if(b.row<15){++b.row;b.X=1;break b}break;case 3:}b.Z<2&&(b.Z=2,b.row<b.Z&&(b.row=b.Z));W=b.row-b.Z+1;$Z(b,U);fZ1(b,W,W+1,b.Z-1);O6(b,b.row,1)}break;case 46:O6(c.A,0,15);break;case 47:b=c,$Z(b.X,U),b.A.updateTime(b.O.time+0),U=b.A,b.A=b.X,b.X=U,OdC(b)}break;case 7:switch(W){case 33:case 34:case 35:U=c.Z,(U.X+=W&3)>32&&(U.X=32)}}},weg=function(b,W,c,U,u,I,D){var h=I[0],K=D[h.getAttribute("p")];
if(K.d_===1){var m=I[1],F=I[2];I=I[3];h.getAttribute("t");m.getAttribute("t");F.getAttribute("t");I.getAttribute("t");h.getAttribute("p");m.getAttribute("p");I.getAttribute("p");D=D[F.getAttribute("p")];h=yD2(h.textContent,m.textContent,F.textContent,I.textContent,D);return new wx(b,W,u,c,h,U,K)}switch(K.d_){case 9:case 10:K.textEmphasis=1;break;case 11:K.textEmphasis=2;break;case 12:K.textEmphasis=3;break;case 13:K.textEmphasis=4;break;case 14:K.textEmphasis=5}return new wx(b,W,u,c,h.textContent||
"",U,K)},yD2=function(b,W,c,U,u){var I=g.n3(),D=I?g.Cc("DIV"):g.Cc("RUBY"),h=g.Cc("SPAN");
h.textContent=b;D.appendChild(h);b=I?g.Cc("DIV"):g.Cc("RP");b.textContent=W;D.appendChild(b);W=I?g.Cc("DIV"):g.Cc("RT");W.textContent=c;D.appendChild(W);c=u.d_;if(c===10||c===11||c===12||c===13||c===14)if(g.KK(W,"text-emphasis-style","filled circle"),g.KK(W,"text-emphasis-color","currentcolor"),g.KK(W,"webkit-text-emphasis","filled circle"),u.d_===11||u.d_===13)g.KK(W,"webkit-text-emphasis-position","under left"),g.KK(W,"text-emphasis-position","under left");c=!0;if(u.d_===4||u.d_===7||u.d_===12||
u.d_===14)g.KK(D,"ruby-position","over"),g.KK(D,"-webkit-ruby-position","before");else if(u.d_===5||u.d_===6||u.d_===11||u.d_===13)g.KK(D,"ruby-position","under"),g.KK(D,"-webkit-ruby-position","after"),c=!1;u=I?g.Cc("DIV"):g.Cc("RP");u.textContent=U;D.appendChild(u);I&&(U=c,g.KK(D,{display:"inline-block",position:"relative"}),I=D.firstElementChild.nextElementSibling,g.KK(I,"display","none"),I=I.nextElementSibling,g.KK(I,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.KK(D.lastElementChild,"display","none"),U?(g.KK(D,"padding-top","0.6em"),g.KK(I,"top","0")):(g.KK(D,"padding-bottom","0.6em"),g.KK(I,"bottom","0")));return D},jhm=function(b){var W="_"+jf++;
return new E6(0,0x8000000000000,0,W,b)},lO=function(b,W){b=b.getAttribute(W);
if(b!=null)return Number(b)},ef=function(b,W){b=b.getAttribute(W);
if(b!=null)return b==="1"},TY=function(b,W){b=lO(b,W);
return b!==void 0?b:null},B3=function(b,W){b=b.getAttribute(W);
if(b!=null)return J8.test(b),b},EB$=function(b,W){var c={},U=W.getAttribute("ws");
Object.assign(c,U?b.U[U]:b.A);b=TY(W,"mh");b!=null&&(c.z9=b);b=TY(W,"ju");b!=null&&(c.textAlign=b);b=TY(W,"pd");b!=null&&(c.nj=b);b=TY(W,"sd");b!=null&&(c.q8=b);b=B3(W,"wfc");b!=null&&(c.windowColor=b);W=lO(W,"wfo");W!==void 0&&(c.windowOpacity=W/255);return c},lZY=function(b,W){var c={},U=W.getAttribute("wp");
U&&Object.assign(c,b.N[U]);b=TY(W,"ap");b!=null&&(c.FE=b);b=lO(W,"cc");b!=null&&(c.dB=b);b=lO(W,"ah");b!=null&&(c.pk=b);b=lO(W,"rc");b!=null&&(c.Uu=b);W=lO(W,"av");W!=null&&(c.fW=W);return c},eMZ=function(b,W,c,U){var u={};
Object.assign(u,lZY(b,W));Object.assign(u,EB$(b,W));U?g.Xa(u,b.A)?(U=b.Y,u=b.A):U="_"+jf++:U=W.getAttribute("id")||"_"+jf++;b=lO(W,"t")+c;W=lO(W,"d")||0x8000000000000;if(u.nj===2||u.nj===3)c=u.Uu,u.Uu=u.dB,u.dB=c;return new E6(b,W,0,U,u)},NS=function(b){b=g.CZ(Math.round(b),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-b.length)+b},TSw=function(b,W,c,U,u){U===0&&(U=0x8000000000000);
var I={};W.wpWinPosId&&Object.assign(I,b.A.get(W.wpWinPosId));W.wsWinStyleId&&Object.assign(I,b.Y.get(W.wsWinStyleId));b=W.rcRowCount;b!==void 0&&(I.Uu=b);W=W.ccColCount;W!==void 0&&(I.dB=W);if(I.nj===2||I.nj===3)W=I.Uu,I.Uu=I.dB,I.dB=W;return new E6(c,U,0,u,I)},kZ=function(b){var W=b.byteOffset;
b.byteOffset+=1;return b.Z.getUint8(W)},LX=function(b){var W=b.byteOffset;
b.byteOffset+=4;return b.Z.getUint32(W)},NSm=function(b){if(typeof b==="string")return!1;
b=new JDg(b,0);return BSC(b)},BSC=function(b){if(!(b.byteOffset<b.Z.byteLength)||LX(b)!==1380139777)return!1;
b.version=kZ(b);if(b.version>1)return!1;kZ(b);kZ(b);kZ(b);return!0},kUY=function(b,W){if(!W)return"";
b.L&&b.O.params.q8!==1&&(W*=-1);return`translate${b.L?"X":"Y"}(${W}px)`},Lig=function(b){b.Nk=Array.from(b.element.getElementsByClassName("caption-visual-line"));
for(var W=b.O.params.Uu,c=0,U=0,u=b.Nk.length-1;c<W&&u>-1;){var I=b.Nk[u];U+=b.L?I.offsetWidth:I.offsetHeight;c++;u--}b.O0=U;W=Math;c=W.max;isNaN(b.yj)&&((U=b.Z.dB)?(u=g.Cc("SPAN"),g.Wz(u,"\u2013".repeat(U)),g.KK(u,PUY(b,b.Z.Ha)),b.Y.appendChild(u),b.yj=u.offsetWidth,b.Y.removeChild(u)):b.yj=0);U=b.Y;W=c.call(W,b.yj,b.DB,(b.L?U.offsetHeight:U.offsetWidth)+1);b.VS&&(W=Math.min(W,b.maxWidth));b.qk=W},VM2=function(b,W){Lig(b);
var c=b.Nk.reduce((U,u)=>(b.L?u.offsetWidth:u.offsetHeight)+U,0);
c=b.O0-c;if(c!==b.xv){let U=c>0&&b.xv===0,u=c<b.xv;W||isNaN(c)||U||!u||(g.EB(b.element,"ytp-rollup-mode"),b.Qj(b.element,"transitionend",b.hj));g.KK(b.Y,"transform",kUY(b,c));b.xv=c}Lig(b)},GUC=function(b,W,c,U){var {formatId:u,
Yv:I,startTimeMs:D,durationMs:h}=b.J(W),K={formatId:u,startTimeMs:D,durationMs:h,Xn:I,kr:I},m=SbC(b.EP,K.startTimeMs),F=m>=0?b.EP[m]:null,M=F?F.startTimeMs+F.durationMs:0,t=K.startTimeMs+K.durationMs;!F||K.startTimeMs-M>b.A?b.EP.splice(m+1,0,K):(F.durationMs=Math.max(M,t)-F.startTimeMs,F.kr=Math.max(F.kr,K.kr));U(b.EP);U=g.W_(W);b=b.Y;U=U.buffer.slice(U.byteOffset,U.byteLength+U.byteOffset);W=W.info.A;b.zc?b.N==null?g.z9(b.logger,350058965,"Null loaded track meta data at captions data received"):
c.CL(U,b.N,W*1E3):g.z9(b.logger,350058965,"Null Representation at captions data received")},dxR=function(b,W){b.X=(c,U)=>{if(b.K.S().experiments.Sp("html5_sabr_live_support_subfragmented_captions"))(b.Z?b.Z=b.Z.Y(c):(b.Z=c,nB$(b.Z)),b.Z)?c.info.UB&&(Hd2(b.Z),GUC(b,b.Z,W,U),b.Z=null):g.z9(b.logger,350058965,"Empty slice");
else if(c.info.UB){var u=c;if(b.uk.length>0){for(u=b.uk.shift();b.uk.length>0;)u=u?.Y(b.uk.shift());u=u?.Y(c)}u?(nB$(u),Hd2(u),GUC(b,u,W,U)):g.z9(b.logger,350058965,"Empty slice")}else b.uk.push(c)};
b.K.addEventListener("sabrCaptionsDataLoaded",b.X)},SbC=function(b,W){b=g.Wy(b,{startTimeMs:W},(c,U)=>c.startTimeMs-U.startTimeMs);
return b>=0?b:-b-2},nB$=function(b){try{var W=g.uu(b)*1E3}catch(c){W=b.info.segmentStartTime*1E3}W<0&&(W=b.info.segmentStartTime*1E3);
b.info.segmentStartTime=W/1E3;b.info.A=W/1E3},Hd2=function(b){try{var W=g.K5(b)*1E3}catch(c){W=b.info.O*1E3}W<0&&(W=b.info.O*1E3);
b.info.O=W/1E3;b.info.J=W/1E3},CUb=function(b,W){if(!g.Hk(b)||b.Z!=null&&g.yo(W,b.Z)&&b.Z.Z.rawcc!=null)return!1;
W=!!b.Z&&b.Z.isManifestless&&Object.values(b.Z.Z).some(c=>g.wh(c,"386"));
b=!!b.Z&&!b.Z.isManifestless&&g.wK(b.Z);return W||b},rDv=function(b,W,c){var U=[];
for(let u in b.X.Z){if(!b.X.Z.hasOwnProperty(u))continue;let I=b.X.Z[u];if(g.wh(I,c||null)){let D=I.info.captionTrack;D&&D.languageCode===W&&U.push(I)}}return U.length?U[0]:null},peg=function(b,W){var c=[];
for(let u in b.X.Z){if(!b.X.Z.hasOwnProperty(u))continue;var U=b.X.Z[u];if(g.wh(U,W||null)){let I=U.info.id,D=I,h=`.${I}`,K="",m="";if(U=U.info.captionTrack)I=U.languageCode,D=U.displayName,h=U.vssId,K=U.kind,m=U.id;c.push(new g.pk({id:u,languageCode:I,languageName:D,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:h,kind:K,captionId:m}))}}return c},oBZ=function(b){var W=zMb.length;
if(b.byteLength<W)return!1;b=new Uint8Array(b,0,W);for(let c=0;c<W;c++)if(zMb[c]!==b[c])return!1;return!0},VM=function(b){b=b.split(":");
var W=0;for(let c of b)W=W*60+Number(c);return W*1E3},bqg=function(b,W,c,U){U=Object.assign({z9:0},U);
return new E6(b,W,c,"_"+jf++,U)},WMv=function(b,W,c,U,u,I,D,h,K){switch(D.tagName){case "b":h.bold=!0;
break;case "i":h.italic=!0;break;case "u":h.underline=!0}for(let F=0;F<D.childNodes.length;F++){var m=D.childNodes[F];if(m.nodeType===3)m=new wx(W,c,U,u.id,m.nodeValue,I||F>0,g.Fa(h)?void 0:h),K.push(m),u.Z.push(m);else{let M={};Object.assign(M,h);WMv(b,W,c,U,u,!0,m,M,K)}}},iq2=function(b,W,c){if(typeof W==="string"||NSm(W))return[{trackData:W,
Sf:c}];if(typeof W==="string"&&W.substring(0,6)==="WEBVTT"||typeof W!=="string"&&oBZ(W))return[{trackData:W,Sf:c}];var U=new DataView(W);if(U.byteLength<=8||U.getUint32(4)!==1718909296)return[];var u=g.OI(U);if(b.PZ&&u){var I=g.KH(u),D=g.Zx(u);u=u.segmentNumber;I&&u&&b.PZ.bM(u,I,D)}b=g.$g(U,1835295092);if(!b||!b.length||!b[0].size)return[];I=[];for(D=0;D<b.length;D++)u=b[D],u=new Uint8Array(W,u.dataOffset,u.size-(u.dataOffset-u.offset)),u=g.vo(u),I.push({trackData:u,Sf:c+D*1E3});ctv(U,I,c);return I=
I.filter(h=>!!h.trackData)},uS2=function(b,W,c){b.Z||(b.Z=new Und);
b=b.Z.O(W,c);Math.random()<.01&&g.cB(Error("Deprecated subtitles format in web player: WebVTT"));return b},ctv=function(b,W,c){var U=g.MF(b,0,1836476516),u=9E4;
U&&(u=g.t1(U)||9E4);U=0;var I=g.$g(b,1836019558);for(let h=0;h<I.length;h++){var D=I[h];h<W.length&&(D=g.MF(b,D.dataOffset,1953653094))&&(D=g.MF(b,D.dataOffset,1952867444))&&(D=g.RT(D)/u*1E3,h===0&&(U=D),W[h].Sf=D-U+c||c*h*1E3)}},sZ2=function(b){var W={};
if(b=g.bL(b))W.lang=b,g.DF2.test(b)&&(W.nj=1);return W},Sf=function(b){return b.O==="HLS"&&b.Gn?!0:b.E0&&b.Gn&&b.O!=="LIVE"&&b.O!=="SABR_LIVE"},IBR=function(b){return!b.A&&b.E0&&b.zn&&(b.O==="LIVE"||b.O==="SABR_LIVE")},GY=function(b,W,c=!1){var U=b.G.j("enable_player_captions_new_style_defaults")?Dnm:hRy,u=U.Ha;
b.Y={};Object.assign(b.Y,U);b.Y.Ha={};Object.assign(b.Y.Ha,u);b.L={Ha:{}};var I=W.backgroundOverride?b.L:b.Y,D=W.background||u.background;J8.test(D);I.Ha.background=D;I=W.colorOverride?b.L:b.Y;D=W.color||u.color;J8.test(D);I.Ha.color=D;I=W.windowColorOverride?b.L:b.Y;D=W.windowColor||U.windowColor;J8.test(D);I.windowColor=D;I=W.backgroundOpacityOverride?b.L:b.Y;D=W.backgroundOpacity;D==null&&(D=u.backgroundOpacity);I.Ha.backgroundOpacity=D;I=W.fontSizeIncrementOverride?b.L:b.Y;D=W.fontSizeIncrement;
D==null&&(D=u.fontSizeIncrement);I.Ha.fontSizeIncrement=D;D=W.fontStyleOverride?b.L:b.Y;I=W.fontStyle;I==null&&(I=u.bold&&u.italic?3:u.bold?1:u.italic?2:0);D=D.Ha;switch(I){case 1:D.bold=!0;delete D.italic;break;case 2:delete D.bold;D.italic=!0;break;case 3:D.bold=!0;D.italic=!0;break;default:delete D.bold,delete D.italic}I=W.textOpacityOverride?b.L:b.Y;D=W.textOpacity;D==null&&(D=u.textOpacity);I.Ha.textOpacity=D;I=W.windowOpacityOverride?b.L:b.Y;D=W.windowOpacity;D==null&&(D=U.windowOpacity);I.windowOpacity=
D;U=W.charEdgeStyleOverride?b.L:b.Y;I=W.charEdgeStyle;I==null&&(I=u.charEdgeStyle);U.Ha.charEdgeStyle=I;U=W.fontFamilyOverride?b.L:b.Y;I=W.fontFamily;I==null&&(I=u.fontFamily);U.Ha.fontFamily=I;b.loaded&&b.o1();c&&g.JF("yt-player-caption-display-settings",W,2592E3)},nX=function(b,W,c){W&&!b.D?(W=jhm({nj:0,
lang:"en"}),b.D=[W,new wx(W.start,W.end-W.start,0,W.id,c??"Captions look like this")],b.player.A4(b.D)):!W&&b.D&&(KMw(b,b.D),b.D=null)},Psm=function(b){if(b.G.j("enable_player_captions_persistence_state_machine")){var W=g.BQ("yt-player-caption-persistence");
if(W==null){let c=g.p$().jp(65);if(c===!0)W=!1;else{let U=g.q_(b.G)?H3(b):ZqD(b);U!=null?W=!!U:c===!1&&(W=!0)}W!==void 0&&dx(b,W)}return W}},H3=function(b){if(!b.K.isInline())return g.BQ("yt-player-sticky-caption")},ZqD=function(b){if(!b.storage)return null;
try{var W=b.storage.get("module-enabled")}catch(c){b.storage.remove("module-enabled")}return W},CX=function(b){if(b.G.j("enable_player_captions_persistence_state_machine"))return Psm(b);
var W=void 0,c=g.p$().jp(65);if(g.q_(b.G)&&c!=null){if(H3(b)!=null)return!1;W=!c}return W},Yv2=function(b){if(b.G.R7===1||b.videoData.Rh===1||g.lB(b.videoData,"yt:cc")==="alwayson")return!0;
if(b.videoData.captionTracks.length)var W=b.getAudioTrack().X;if(b.G.j("enable_player_captions_persistence_state_machine")){var c=Psm(b);if(c!==void 0)return!!c}else if(b.G.R7===2&&(g.q_(b.G)?c=H3(b):c=ZqD(b),c!=null))return!!c;c=t8(b.player.getAudioTrack(),g.q_(b.G));var U=g.lB(b.videoData,"yt:cc");if(CX(b)===void 0){if(c==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return U?U==="on":!0;if(c==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return U==="on"}else return U==="on";return W==="ON"||g.lB(b.videoData,
"yt:cc")==="on"},rx=function(b,W=!1){if(b.X&&!W||!b.videoData.captionTracks.length)return!1;
b=b.getAudioTrack();return!!b.Z||b.X==="FORCED_ON"},mnd=function(b){return b.G.j("html5_honor_caption_availabilities_in_audio_track")&&b.O!=="LIVE"&&b.O!=="SABR_LIVE"},FMw=function(b,W){if(b.X){var c=b.K.yz().Pr().textTracks,U=null;
b.O==="HLS"?U=b.X.getId():U=b.X.toString();for(let I=0;I<c.length;I++){var u=c[I];u.id===U&&(W?u.mode!=="showing"&&(u.mode="showing",u=b.X,b.gf(u,!!u,pX(b)?"g":b.N?"m":"s")):u.mode==="showing"&&(u.mode="disabled"))}}},pX=function(b){var W=zY(b);
return!!W&&b.X===W},M11=function(b,W){if(b.O==="HLS")return!1;
g.SV(b.videoData)&&(W=!0);W||(W=b.O==="TTS"?!1:b.O==="INNERTUBE"?!1:!0);return W||b.G.j("web_watch_disable_account_level_captions_settings")&&g.q_(b.G)?!0:!!g.p$().jp(66)},zY=function(b){return b.U&&b.U.Z},os=function(b,W){if(!b.Z)return null;
if(b.U&&b.U.A)return b.U.A;W=M11(b,W);W=b.Z.Z.Z(W);var c=null;if(HpY(b.G)){var U=b.K.isInline()?void 0:g.BQ("yt-player-caption-sticky-language");var u=[U,b.videoData.captionsLanguagePreference,b.G.captionsLanguagePreference,g.lB(b.videoData,"yt:cc_default_lang")];let h=!1;for(let K=0;K<u.length;K++){let m=u[K];if(m){h=!0;for(var I=0;I<W.length;I++)if(g.bL(W[I])===m)return W[I];for(I=0;I<W.length;I++)if(g.bL(W[I]).split("-")[0]===m.split("-")[0])return W[I]}}if(h&&b.Z&&(u=b.Z.U,u.length))for(var D of u)if(D.languageCode===
U){c=D;break}}else for(D=[b.videoData.captionsLanguagePreference,b.G.captionsLanguagePreference,g.lB(b.videoData,"yt:cc_default_lang")],U=0;U<D.length;U++)for(u=0;u<W.length;u++)if(g.bL(W[u])===D[U])return W[u];D=null;b.U&&b.U.O&&(D=b.U.O);D||(D=W.find(h=>h.isDefault)||null);
D||(D=W[0]||zY(b));D&&c&&g.bL(D).split("-")[0]!==c.languageCode.split("-")[0]&&(D=nCw(D,c));return D},ghv=function(b,W){var c=b.Z.Z.Z(!0),U=[];
for(let u=0;u<c.length;u++){let I=c[u],D=g.Cc("TRACK");D.setAttribute("kind","subtitles");D.setAttribute("label",g.oM(I));D.setAttribute("srclang",g.bL(I));D.setAttribute("id",I.toString());b.zc||D.setAttribute("src",b.Z.L(I,"vtt"));I===W&&D.setAttribute("default","1");U.push(D)}W=b.K.yz();W.qk(U);U=W.Pr();b.zn&&b.L9.Qj(U.textTracks,"change",b.A$)},i1=function(b,W,c){b.loaded&&b.unload();
c!=null&&(b.N=c,b.N&&(b.G.j("enable_player_captions_persistence_state_machine")?dx(b,!!W):g.q_(b.G)?b1(b,!!W):W2(b,!!W)));W!==null||rx(b,!0)||b.gf(W,!!W,b.N?"m":"s");b.X=W;rx(b)&&(b.X=zY(b));c2(b,b.X??void 0);b.load()},dx=function(b,W){b.G.j("enable_player_captions_persistence_state_machine")&&g.JF("yt-player-caption-persistence",W,3122064E3)},b1=function(b,W){b.K.isInline()||g.JF("yt-player-sticky-caption",W,2592E3)},W2=function(b,W){if(b.storage)try{b.storage.set("module-enabled",W)}catch(c){}},
c2=function(b,W){b.G.j("html5_modify_caption_vss_logging")&&(b.videoData.m2=W)},t1g=function(b,W){var c=b.qk[W.id];
c&&c.O!==W&&(c.dispose(),delete b.qk[W.id],c=null);c||(c=XiY(b,W))&&(b.qk[W.id]=c)},xny=function(b,W){var c=W.windowId;
b.Vj[c]||(b.Vj[c]=[]);b.Vj[c].push(W)},XiY=function(b,W){var c=Atm(b);
if(!c)return null;var U=b.X?g.bL(b.X):null;U&&g.DF2.test(U)&&(W.params.nj=1);var u=b.mx.getPlayerSize();U=u.height*b.O0.height;u=u.width*b.O0.width;b.G.playerStyle!=="google-live"||b.Y.isDefault||Object.assign(W.params,b.Y);switch(W.params.z9!=null?W.params.z9:W.Z.length>1?1:0){case 1:return new vh1(W,b.Y,b.L,c.width,c.height,u,U,b.G.experiments,b.nu.bind(b),b.K);case 2:return new RRZ(W,b.Y,b.L,c.width,c.height,u,U,b.G.experiments,b.nu.bind(b),b.K);default:return new Uk(W,b.Y,b.L,c.width,c.height,
u,U,b.G.experiments,b.nu.bind(b),b.K)}},Atm=function(b){var W=b.mx.getVideoContentRect(!0).height,c=b.mx.getVideoContentRect(!0).width;
if(!W||!c)return null;W*=b.O0.height;c*=b.O0.width;return{width:c,height:W}},KMw=function(b,W){b.player.Bn(W);
for(let c of W)g.H6(b.Nk,c);gx(b.yj)},qv$=function(b,W){if(!b.Z)return{};
if(W){g.Fa(W)||b.D3(W.vss_id,"m");if(b.A&&b.O!=="HLS"||!g.R$(W))return;if(g.Fa(W)){i1(b,null,!0);return}let U;var c=b.Z.Z.Z(!0);for(let u=0;u<c.length;u++){let I=c[u];I.languageCode!==W.languageCode||U&&(I.languageName!==W.languageName||(I.captionId||"")!==(W.captionId||"")||g.oM(I)!==W.displayName)||(U=W.translationLanguage?nCw(I,W.translationLanguage):I)}b.VZ(W.position);!U||U===b.X&&b.loaded||(W=g.OX(),c=g.bL(U),W.length&&c===W[W.length-1]||(W.push(c),g.JF("yt-player-caption-language-preferences",
W)),HpY(b.G)&&!b.K.isInline()&&g.JF("yt-player-caption-sticky-language",c,2592E3),i1(b,U,!0))}else return b.loaded&&b.X&&!pX(b)?XX(b.X):{};return""};
g.qW.prototype.bM=g.i2(134,function(b,W,c){this.X.set(b,{zs:W,wQ:c})});
g.$I.prototype.bM=g.i2(133,function(b,W,c){this.L9.bM(b,W,c)});
g.KR.prototype.U=g.i2(132,function(){this.mediaElement.U()});
g.sA.prototype.U=g.i2(131,function(){var b=g.ws(document,"track",void 0,this.Z);for(let W=0;W<b.length;W++)g.ow(b[W])});
g.KR.prototype.xv=g.i2(130,function(){return this.mediaElement.xv()});
g.sA.prototype.xv=g.i2(129,function(){return!(!this.Z.textTracks||!this.Z.textTracks.addEventListener)});
g.KR.prototype.Vj=g.i2(128,function(){return this.mediaElement.Vj()});
g.sA.prototype.Vj=g.i2(127,function(){return!!this.Z.textTracks});
g.KR.prototype.qk=g.i2(126,function(b){this.mediaElement.qk(b)});
g.sA.prototype.qk=g.i2(125,function(b){for(let W=0;W<b.length;W++)this.Z.appendChild(b[W])});
g.py.prototype.D3=g.i2(48,function(b,W){this.app.Hk().D3(b,W)});
g.Ls.prototype.D3=g.i2(47,function(b,W){this.C.D3(b,W)});
g.YI.prototype.D3=g.i2(46,function(b,W){b=[b,W];g.$5(this,g.fA(this.provider),"cfi",b)});
g.MW.prototype.D3=g.i2(45,function(b,W){this.qoe&&this.qoe.D3(b,W)});
g.kk.prototype.D3=g.i2(44,function(b,W){this.uo.D3(b,W)});
g.Ap.prototype.D3=g.i2(43,function(){});
g.N8.prototype.D3=g.i2(42,function(b,W){g.m2(this,37,[b,W])});
g.py.prototype.gf=g.i2(41,function(b,W,c){this.app.Hk().gf(b,W,c)});
g.Ls.prototype.gf=g.i2(40,function(b,W,c){this.C.gf(b,W,c)});
g.YI.prototype.gf=g.i2(39,function(b,W,c){if(this.Wk!==b||this.R$!==W)W=W==="rawcc"?"":W,c=[b,W,this.Wk,c],g.$5(this,g.fA(this.provider),"cfs",c),this.Wk=b,this.R$=W});
g.MW.prototype.gf=g.i2(38,function(b,W,c){this.qoe&&this.qoe.gf(b,W,c)});
g.kk.prototype.gf=g.i2(37,function(b,W,c){this.uo.gf(b,W,c)});
g.Ap.prototype.gf=g.i2(36,function(){});
g.N8.prototype.gf=g.i2(35,function(b,W,c){g.m2(this,36,[b,W,c])});
g.Cb.prototype.QX=g.i2(11,function(){return this.PZ});
g.OC.prototype.QX=g.i2(10,function(){return this.Hk().T7()});
g.py.prototype.T7=g.i2(9,function(){return this.app.QX()});
g.Ls.prototype.T7=g.i2(8,function(){return this.C.T7()});
g.kk.prototype.T7=g.i2(7,function(){return this.loader?.QX()||null});
g.Ap.prototype.T7=g.i2(6,function(){return null});
g.N8.prototype.T7=g.i2(5,function(){return null});
g.Tc.prototype.lD=g.i2(3,function(b){return(b=this.O(b))?b.Z:0});
g.zz.prototype.lD=g.i2(2,function(){return 0});
var ptb=/#(.)(.)(.)/,r4b=/^#(?:[0-9a-f]{3}){1,2}$/i,$n1=class{constructor(){this.O=[];this.X=[]}Z(b){return b?this.X.concat(this.O):this.X}},u1=class extends g.SJ{constructor(b){super();this.uX=b;this.Z=new $n1;this.qk=new $n1;this.A=null;this.U=[];this.O0=[]}J(){}Y(){}O(){}L(){return""}L9(){return!1}FO(b,W){if(this.uX.S().j("html5_dispatch_tracklist_loaded_event")){this.A&&(this.A.reject(),this.A=null);var c=[];this.uX.p9("trackListLoaded",this.Z,c,W);this.uX.S().j("enable_po_decoration_of_forced_tracks")&&
this.uX.p9("trackListLoaded",this.qk,c,W);c.length?(W=new g.Tu,W.promise.then(b.FO,()=>{}),this.A=W,Promise.all(c).then(W.resolve,W.reject).finally(()=>{this.A=null})):b.FO()}else b.FO()}Ax(){this.A&&(this.A.reject(),this.A=null);
this.O();super.Ax()}},aBD={en:"English"},fBg=class extends u1{constructor(b){super(b);this.X=new Set}Y(b){var W=this.uX.yz();if(W&&W.Pr()){W=W.Pr().textTracks;for(let c of W)c.kind==="subtitles"&&!this.X.has(c.language)&&c.language&&(v3(this.Z,new g.pk({languageCode:c.language,languageName:c.language,kind:c.kind,id:c.id,displayName:aBD[c.label]||c.label,vss_id:`.${c.language}`})),this.X.add(c.language))}this.Z.Z().length>0&&b.FO()}},Oq2=class extends u1{constructor(b,W,c){super(b);this.videoData=
W;this.audioTrack=c;this.X=null;this.N=0;this.D=!1;this.U=W.CA;this.O0=W.Xe;this.D=g.SV(W)}J(b,W,c){this.I1();this.O();cDw(this,b,W,c)}Y(b){if(this.audioTrack){for(let W of this.audioTrack.captionTracks)v3(this.Z,W);this.audioTrack.Z&&v3(this.qk,this.audioTrack.Z)}this.FO(b,this.videoData.videoId)}L(b,W){var c=b.jV(),U={fmt:W};if(W==="srv3"||W==="3"||W==="json3")g.n3()?Object.assign(U,{xorb:2,xobt:1,xovt:1}):Object.assign(U,{xorb:2,xobt:3,xovt:3});b.translationLanguage&&(U.tlang=g.bL(b));this.D&&
(U.xosf="1");Object.assign(U,this.uX.S().Z);return g.dQ(c,U)}O(){this.N++;this.X&&(this.X.abort(),this.X=null)}},QZd=class{constructor(){this.segments=[]}contains(b){b=g.Wy(this.segments,b);return b>=0||b<0&&(-b-1)%2===1}length(){return this.segments.length/2}},ytd=class extends g.SJ{constructor(b,W,c,U,u,I){super();this.policy=b;this.player=W;this.B=c;this.N=U;this.Y=u;this.zc=I;this.A=new QZd;this.L=-1;this.X=this.O=this.Z=null;this.O0=0;this.J=new g.a2(this.U,1E3,this);this.events=new g.Bp(this);
g.B(this,this.J);g.B(this,this.events);this.events.Qj(W,"SEEK_COMPLETE",this.D);this.D();this.U()}Ax(){super.Ax();this.X&&this.X.cancel()}D(){this.seekTo(this.player.getCurrentTime())}seekTo(b){b-=this.player.NH();var W=this.Z;this.Z=g.jw(this.B.J(b).K9);W!==this.Z&&this.zc&&this.zc()}reset(){this.A=new QZd;this.L=-1;this.X&&(this.X.cancel(),this.X=null)}U(){this.I1();var b;if(b=this.Z!=null)b=this.Z,b=b.B.A(b);if(b&&!this.X&&!(this.Z&&this.Z.segmentStartTime-this.player.getCurrentTime()>30)){b=this.Z;
b=b.B.E0(b);let u=b.K9[0];if(this.player.getVideoData().enableServerStitchedDai){var W=this.player.T7();if(W){var c=u.B.info.id;let I=u.Yv;var U=b.K9[0].A;if(this.policy.yj){if(W=g.lGw(W,U,I,c,3))b.A=W}else if(c=W.G1(U,I,c,3))if(U=2,W.wJ.has(I)?U=0:g.EA(W,I)&&(U=1),W=U,W===0)c&&(b.Z=new g.nI(c));else if(W===2){this.J.start();Uxy(this)&&this.seekTo(this.player.getCurrentTime());return}}}u.B.index.Jr(u.Yv)?(this.A.contains(b.K9[0].Yv)||uq2(this,b),this.Z=g.jw(b.K9)):Uxy(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()}},
wib=class extends u1{constructor(b,W){super(W);this.X=b;this.K=W;this.N=null;this.D=!1;this.logger=new g.pD("caps");this.zc=g.yo(this.K,this.X)}J(b,W,c){this.O();W=shv(this,b.getId());W||(W=b.languageCode,W=this.X.isManifestless?IZ1(this,W,"386"):IZ1(this,W));if(W){var U=(W.index.lD(W.index.FC())-W.index.getStartTime(W.index.FC()))*1E3,u=new g.xY1(this.K.S());this.N=new ytd(u,this.K,W,(I,D)=>{c.CL(I,b,D,U)},this.zc||g.Pm(W.info),()=>{this.N&&this.N.reset();
this.D=!0})}}L9(){var b=this.D;
this.D=!1;return b}Y(b){var W=this.K.S().j("html5_fallback_if_rawcc_missing");var c=this.X.Z.rawcc!=null;if(!this.zc||!c&&W)W=this.X.isManifestless?DxD(this,"386"):DxD(this);else{if(!c){g.z9(this.logger,386248249,"rawcc used but unavailable");return}W=[new g.pk({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.pk({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let U of W)v3(this.Z,
U);b.FO()}O(){this.N&&(this.N.dispose(),this.N=null)}L(){return""}},jZy=class extends u1{constructor(b,W,c,U,u,I){super(b);this.videoId=c;this.D=u;this.eventId=I;this.zc={};this.X=null;b=U||g.nx(W).hl||"";b=b.split("_").join("-");this.N=g.dQ(W,{hl:b})}J(b,W,c){this.I1();W=this.L(b,W);this.O();this.X=g.gU(W,{format:"RAW",onSuccess:U=>{this.X=null;var u=U.getResponseHeader&&U.getResponseHeader("Content-Length")?Number(U.getResponseHeader("Content-Length")):0;c.CL(U.responseText,b,void 0,void 0,u)},
withCredentials:!0})}Y(b){var W=this.N,c={type:"list",tlangs:1,v:this.videoId,vssids:1};this.D&&(c.asrs=1);W=g.dQ(W,c);this.O();this.X=g.gU(W,{format:"RAW",onSuccess:U=>{this.X=null;if((U=U.responseXML)&&U.firstChild){var u=U.getElementsByTagName("track");for(var I=0;I<u.length;I++){var D=u[I],h=D.getAttribute("lang_code");let K=D.getAttribute("lang_translated"),m=D.getAttribute("name"),F=D.getAttribute("kind"),M=D.getAttribute("id"),t=D.getAttribute("lang_default")==="true",v=D.getAttribute("cantran")===
"true";D=D.getAttribute("vss_id");v3(this.Z,new g.pk({languageCode:h,languageName:K,name:m,kind:F,id:M,is_servable:!0,is_translateable:v,vss_id:D,is_default:t}))}U=U.getElementsByTagName("target");u=U.length;for(I=0;I<u;I++)h={languageCode:U[I].getAttribute("lang_code"),languageName:U[I].getAttribute("lang_translated"),languageOriginal:U[I].getAttribute("lang_original"),id:U[I].getAttribute("id"),isDefault:U[I].getAttribute("lang_default")==="true"},this.zc[h.languageCode]=h.languageName,this.U.push(h)}this.FO(b,
this.videoId)},
withCredentials:!0})}L(b,W){var c=this.N;W={v:this.videoId,type:"track",lang:b.languageCode,name:b.getName(),kind:b.kind,fmt:W};var U=this.uX.S();U.j("captions_url_add_ei")&&(W.ei=this.eventId);b.translationLanguage&&(W.tlang=g.bL(b));Object.assign(W,U.Z);return c=g.dQ(c,W)}O(){this.X&&this.X.abort()}},J8=/^#(?:[0-9a-f]{3}){1,2}$/i;var Ehm=["left","right","center","justify"];var wx=class extends g.bz{constructor(b,W,c,U,u,I=!1,D=null){super(b,b+W,{priority:c,namespace:"captions"});this.windowId=U;this.text=u;this.append=I;this.Z=D}toString(){return super.toString()}};var Uk=class extends g.IQ{constructor(b,W,c,U,u,I,D,h,K,m){var F=m.isInline()&&!0,M={};Object.assign(M,W);Object.assign(M,b.params);Object.assign(M,c);var t={};Object.assign(t,W.Ha);b.params.Ha&&Object.assign(t,b.params.Ha);Object.assign(t,c.Ha);F&&(t.background&&(M.windowColor=t.background),M.windowOpacity=.6,t.backgroundOpacity=0);M.Ha=t;var v=M.nj===1,R=[{V:"span",X_:"captions-text",Jx:{style:"word-wrap: normal; display: block;"}}],e=h.Sp("caption_edit_on_hover")&&m.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
e&&R.unshift({V:"button",X_:"caption-edit",Jx:{tabindex:"0","aria-label":zhY()},hx:[{V:"svg",Jx:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},hx:[{V:"path",Jx:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({V:"div",X_:"caption-window",Jx:{id:`caption-window-${b.id}`,dir:v?"rtl":"ltr",tabindex:"0",lang:M.lang},hx:R});
this.experiments=h;this.U=[];this.E0=!1;this.O=b;this.Vj=this.bX=null;this.Hn=I;this.BP=D;this.J=null;this.maxWidth=I*.96;this.maxHeight=D*.96;this.Z=M;this.bW=c;this.L9=W;this.Y=this.Gc("captions-text");b=this.Y.style;this.Wk=h.Sp("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in b||"WebkitBoxDecorationBreak"in b);this.vk=hMR(U,u,I,D);this.MI=K;e&&(this.N=this.Gc("caption-edit"),this.Qj(this.N,"click",()=>{this.MI()}));
this.type=0;this.nu=this.vk*Kiy(t);this.zn=F;this.mx=h.Sp("enable_centered_caption_for_tvfilm_video")&&m.getVideoData().isTvfilmVideo;this.zc=m.S().Tc().Z.jp(g.Tp1);this.VS=m.S().Tc().Z.jp(g.JI1);U=new g.X5(this.element,!0);g.B(this,U);U.subscribe("dragstart",this.mU,this);U.subscribe("dragmove",this.AK,this);U.subscribe("dragend",this.SV,this);this.HZ=this.j7=this.R$=this.fu=0;U="";this.Z.windowOpacity&&(U=xZ(this.Z.windowColor),U="rgba("+U[0]+","+U[1]+","+U[2]+","+this.Z.windowOpacity+")");u={"background-color":U,
display:this.Z.isVisible===!1?"none":"","text-align":Ehm[this.Z.textAlign]};this.Wk&&(u["border-radius"]=U?`${this.nu*.25}px`:"");(this.L=this.O.params.nj===2||this.O.params.nj===3)&&ZdZ(this,this.element);g.KK(this.element,u);F&&this.element.parentElement?.style.setProperty("--caption-window-color",U);switch(this.Z.FE){case 0:case 1:case 2:g.EB(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.EB(this.element,"ytp-caption-window-bottom")}}mU(b,W){this.j7=b;this.HZ=W;var c=g.AT(this.element,
this.element.parentElement);this.fu=b-c.x;this.R$=W-c.y}AK(b,W){if(b!==this.j7||W!==this.HZ){g.je(this.element,"ytp-dragging")||g.EB(this.element,"ytp-dragging");var c=g.$O(this.element);b=b-this.fu-.02*this.Hn;var U=W-this.R$-.02*this.BP,u=(b+c.width/2)/this.maxWidth*3;u=Math.floor(g.CZ(u,0,2));var I=(U+c.height/2)/this.maxHeight*3;I=Math.floor(g.CZ(I,0,2));W=u+I*3;b=(b+u/2*c.width)/this.maxWidth;b=g.CZ(b,0,1)*100;c=(U+I/2*c.height)/this.maxHeight;c=g.CZ(c,0,1)*100;this.O.params.FE=W;this.O.params.fW=
c;this.O.params.pk=b;this.O.params.isDefault=!1;this.Z.FE=W;this.Z.fW=c;this.Z.pk=b;this.Z.isDefault=!1;this.L9.FE=W;this.L9.fW=c;this.L9.pk=b;this.L9.isDefault=!1;this.f3()}}SV(){g.ee(this.element,"ytp-dragging")}f3(){this.D(this.U)}D(b){var W=this.zn?0:Math.min(this.A$(),this.maxWidth),c=this.gC(),U=this.zn;if(U){var u=getComputedStyle(this.Y.parentNode);u=qS(u.borderLeftWidth)+qS(u.borderRightWidth)+qS(u.paddingLeft)+qS(u.paddingRight)}else u=0;var I="";this.O.params.nj===3&&(I="rotate(180deg)");
var D=U?`calc(96% - ${u}px)`:"96%";g.KK(this.element,{top:0,left:0,right:"",bottom:"",width:W?`${W}px`:"",height:c?`${c}px`:"","max-width":D,"max-height":D,margin:"",transform:""});this.o1(b);I={transform:I,top:"",left:"",width:W?`${W}px`:"",height:c?`${c}px`:"","max-width":"","max-height":""};D=this.Z.FE;var h=this.Z.pk,K=this.Z.fW;this.mx&&D!=null&&(h=50,D=Math.floor(D/3)*3+1);h=h*.96+2;switch(D){case 0:case 3:case 6:(U=this.Z.Ha.fontSizeIncrement)&&U>0&&this.Z.nj!==2&&this.Z.nj!==3&&(h=Math.max(h/
(1+U*2),2));I.left=`${h}%`;break;case 1:case 4:case 7:I.left=`${h}%`;let m=0;this.zc||(m=this.Y.offsetWidth);W||m?(W=W||m+1,I.width=`${W}px`,I["margin-left"]=U?`${W/-2-u/2}px`:`${W/-2}px`):(this.zc&&(I.width="max-content"),I.transform+=" translateX(-50%)");break;case 2:case 5:case 8:I.right=`${100-h}%`}U=K*.96+2;switch(D){case 0:case 1:case 2:I.top=`${U}%`;break;case 3:case 4:case 5:I.top=`${U}%`;U=0;this.zc||(U=this.element.clientHeight);(c=c||U)?(I.height=`${c}px`,I["margin-top"]=`${c/-2}px`):I.transform+=
" translateY(-50%)";break;case 6:case 7:case 8:I.bottom=`${100-U}%`}if(this.VS){switch(D){case 0:case 3:case 6:c=Math.max(0,100-2*h);break;case 2:case 5:case 8:c=Math.max(0,100-2*(100-h));break;default:c=Math.max(0,2*Math.min(h-2,98-h))}I["max-width"]=u>0?`calc(${c}% - ${u}px)`:`${c}%`}g.KK(this.element,I);this.N&&(this.zc?c=this.nu:(b=Ybb(this,b),c=this.mx?b>0?this.Y.offsetHeight/b:0:this.Y.offsetHeight/b),this.N.style.height=`${c}px`,this.N.style.width=`${c}px`,this.element.style.paddingLeft=`${c+
5}px`,this.element.style.paddingRight=`${c+5}px`,this.zc||(b=Number(this.element.style.marginLeft.replace("px",""))-c-5,c=Number(this.element.style.marginRight.replace("px",""))-c-5,this.element.style.marginLeft=`${b}px`,this.element.style.marginRight=`${c}px`))}o1(b){if(this.type===0&&this.O.params.Uu!==void 0&&this.experiments.Sp("web_enable_popon_asr_captions")){var W=b,c=this.O.params.Uu;if(W.length===0||c<=0)b=[];else{b=[];for(let u=W.length-1;u>=0;u--){var U=W[u];b.unshift(U);let I=Ybb(this,
b);if(I>c){b.shift();typeof U.text==="string"&&(W=U.text.split("\n"),c=I-c,W.length-c>0&&(U=new wx(U.start,U.end-U.start,U.priority||0,U.windowId,W.slice(c).join("\n"),U.append,U.Z),b.unshift(U)));break}}}}for(U=0;U<b.length&&b[U]===this.U[U];U++);if(this.E0||this.U.length>U)U=0,this.E0=!1,this.U=[],this.J=this.Vj=this.bX=null,g.pc(this.Y);for(;U<b.length;U++)MMZ(this,b[U])}A$(){return 0}gC(){return 0}toString(){return super.toString()}};var eRv=class{constructor(){this.O=this.time=this.mode=this.X=0;this.A=new lBZ(this);this.Y=new lBZ(this);this.Z=[];this.clear()}clear(){this.O=this.time=this.mode=0;this.Z=[];this.reset()}reset(){this.mode=0;this.A.reset(0);this.Y.reset(1)}},gBZ=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],Tdy=class{constructor(){this.type=0}set(b){this.type=b}get(){return this.type}},Jty=class{constructor(){this.state=this.xE=this.fh=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}wR(){return this.state!==0}matches(b,W){return this.wR()&&b===this.fh&&W===this.xE}},Bd2=class{constructor(){this.timestamp=this.Z=0}reset(){this.timestamp=
this.Z=0}},sk=class{constructor(b){this.Y=b;this.O=[];this.Z=this.X=this.row=0;this.style=new Tdy;this.A=0;for(b=0;b<=15;b++){this.O[b]=[];for(let W=0;W<=32;W++)this.O[b][W]=new Bd2}}updateTime(b){for(let W=1;W<=15;++W)for(let c=1;c<=32;++c)this.O[W][c].timestamp=b}debugString(){var b="\n";for(let W=1;W<=15;++W){for(let c=1;c<=32;++c){let U=this.O[W][c];b=U.Z===0?b+"_":b+String.fromCharCode(U.Z)}b+="\n"}return b}reset(b){for(let W=0;W<=15;W++)for(let c=0;c<=32;c++)this.O[W][c].reset();this.A=b;this.Z=
0;this.X=this.row=1}},vBb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],RM1=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],qb$=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],$xd=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],NdD=class{constructor(b){this.O=b;this.Y=0;this.style=new Tdy;this.L=new sk(this.O);this.J=new sk(this.O);this.text=new sk(this.O);this.X=this.L;this.A=this.J;this.Z=this.X}reset(b,W){this.Y=W;this.style.set(2);this.X=this.L;this.A=this.J;this.Z=this.X;var c=(b<<2)+(W<<1);this.L.reset(c);this.J.reset(c);this.text.reset((b<<
2)+(W<<1)+1)}},lBZ=class{constructor(b){this.Z=b;this.Y=0;this.O=new NdD(this.Z);this.L=new NdD(this.Z);this.X=new Jty;this.A=this.O}reset(b){this.Y=b;this.X.clear();this.A=this.O;this.O.reset(b,0);this.L.reset(b,1)}};var kFw=class{A(){}};var Iy=class extends g.SJ{reset(){}};var E6=class extends g.bz{constructor(b,W,c,U,u){super(b,b+W,{priority:c,namespace:"captions"});this.id=U;this.params=u;this.Z=[]}toString(){return super.toString()}},jf=0;var LMw=class extends Iy{constructor(b){super();this.A=b;this.pens={};this.N={};this.U={};this.Y="_"+jf++;this.J={};this.X=this.Z=null;this.L=!0}reset(){this.J={};this.X=this.Z=null;this.L=!0}O(b,W){b=b.firstChild;b.getAttribute("format");W=W||0;Number.isFinite(W);b=Array.from(b.childNodes);for(var c of b)if(c.nodeType===1)switch(c.tagName){case "head":var U=c;break;case "body":var u=c}if(U){U=Array.from(U.childNodes);for(var I of U)if(I.nodeType===1)switch(I.tagName){case "pen":c=I.getAttribute("id");
U=this.pens;b={};var D=I.getAttribute("p");D&&Object.assign(b,this.pens[D]);D=ef(I,"b");D!=null&&(b.bold=D);D=ef(I,"i");D!=null&&(b.italic=D);D=ef(I,"u");D!=null&&(b.underline=D);D=TY(I,"et");D!=null&&(b.charEdgeStyle=D);D=TY(I,"of");D!=null&&(b.offset=D);D=B3(I,"bc");D!=null&&(b.background=D);D=B3(I,"ec");D!=null&&(b.O9=D);D=B3(I,"fc");D!=null&&(b.color=D);D=TY(I,"fs");D!=null&&D!==0&&(b.fontFamily=D);D=lO(I,"sz");D!==void 0&&(b.fontSizeIncrement=D/100-1);D=lO(I,"bo");D!==void 0&&(b.backgroundOpacity=
D/255);D=lO(I,"fo");D!==void 0&&(b.textOpacity=D/255);D=TY(I,"rb");D!=null&&D!==10&&D!==0&&(b.d_=D>10?D-1:D);D=TY(I,"hg");D!=null&&(b.Un=D);U[c]=b;break;case "ws":U=I.getAttribute("id");this.U[U]=EB$(this,I);break;case "wp":U=I.getAttribute("id"),this.N[U]=lZY(this,I)}}if(u){I=[];u=Array.from(u.childNodes);for(e of u)if(e.nodeType===1)switch(e.tagName){case "w":this.Z=eMZ(this,e,W,!1);(u=this.J[this.Z.id])&&u.end>this.Z.start&&(u.end=this.Z.start);this.J[this.Z.id]=this.Z;I.push(this.Z);break;case "p":var h=
e;b=W;u=[];U=h.getAttribute("w")||this.Y;c=!!ef(h,"a");b=(lO(h,"t")||0)+b;D=lO(h,"d")||5E3;c||(!this.L&&this.X&&this.X.windowId===U&&this.X.end>b&&(this.X.end=b),this.X&&this.X.text==="\n"&&(this.X.text=""));let L=c?6:5;var K=h.getAttribute("p");K=K?this.pens[K]:null;let k=Array.from(h.childNodes);k.length&&(this.L=h.getAttribute("d")!=null);for(h=0;h<k.length;h++){var m=k[h];var F=void 0;h>0&&(c=!0);let S;m.nodeType===1&&(S=m);if(S&&S.tagName==="s"){if((m=(m=S.getAttribute("p"))?this.pens[m]:null)&&
m.d_&&(m.d_===1?(m=k.slice(h,h+4),m.length===4&&(F=weg(b,D,U,c,L,m,this.pens),h+=3)):F=weg(b,D,U,c,L,[S],this.pens)),!F){var M=S;F=b;m=D;var t=U,v=c;let H=M.textContent?M.textContent:"";var R=M.getAttribute("p");R=R?this.pens[R]:null;M=lO(M,"t")||0;F=new wx(F+M,m-M,L,t,H,v,R)}}else F=new wx(b,D,L,U,m.textContent||"",c,K);u.push(F);this.X=F}if(u.length>0){u[0].windowId===this.Y&&(this.Z=eMZ(this,e,W,!0),I.push(this.Z));for(let S of u)S.windowId=this.Z.id,this.Z.Z.push(S),I.push(S)}}var e=I}else e=
[];return e}};var V1g=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),Svv=class extends Iy{constructor(b){super();this.L=b;this.Z=new Map;this.A=new Map;this.Y=new Map;this.X=new Map}reset(){this.X.clear()}O(b,W){b=JSON.parse(b);if(!b)return[];if(b.pens){var c=b.pens,U=0;for(var u of c){c={};var I=u.pParentId;I&&Object.assign(c,this.Z.get(I));u.bAttr&&(c.bold=!0);u.iAttr&&(c.italic=!0);u.uAttr&&(c.underline=!0);I=u.ofOffset;I!=null&&(c.offset=I);u.szPenSize!==void 0&&(c.fontSizeIncrement=u.szPenSize/100-1);
I=u.etEdgeType;I!=null&&(c.charEdgeStyle=I);u.ecEdgeColor!==void 0&&(c.O9=NS(u.ecEdgeColor));I=u.fsFontStyle;I!=null&&I!==0&&(c.fontFamily=I);u.fcForeColor!==void 0&&(c.color=NS(u.fcForeColor));u.foForeAlpha!==void 0&&(c.textOpacity=u.foForeAlpha/255);u.bcBackColor!==void 0&&(c.background=NS(u.bcBackColor));u.boBackAlpha!==void 0&&(c.backgroundOpacity=u.boBackAlpha/255);(I=u.rbRuby)&&I!==10&&(c.d_=I>10?I-1:I,c.textEmphasis=V1g.get(c.d_));u.hgHorizGroup&&(c.Un=u.hgHorizGroup);this.Z.set(U++,c)}}if(b.wsWinStyles){U=
b.wsWinStyles;u=0;for(var D of U)U={},(c=D.wsParentId)?Object.assign(U,this.Y.get(c)):Object.assign(U,this.L),D.mhModeHint!==void 0&&(U.z9=D.mhModeHint),D.juJustifCode!==void 0&&(U.textAlign=D.juJustifCode),D.pdPrintDir!==void 0&&(U.nj=D.pdPrintDir),D.sdScrollDir!==void 0&&(U.q8=D.sdScrollDir),D.wfcWinFillColor!==void 0&&(U.windowColor=NS(D.wfcWinFillColor)),D.wfoWinFillAlpha!==void 0&&(U.windowOpacity=D.wfoWinFillAlpha/255),this.Y.set(u++,U)}if(b.wpWinPositions){u=b.wpWinPositions;D=0;for(var h of u)u=
{},(U=h.wpParentId)&&Object.assign(u,this.A.get(U)),h.ahHorPos!==void 0&&(u.pk=h.ahHorPos),h.apPoint!==void 0&&(u.FE=h.apPoint),h.avVerPos!==void 0&&(u.fW=h.avVerPos),h.ccCols!==void 0&&(u.dB=h.ccCols),h.rcRows!==void 0&&(u.Uu=h.rcRows),this.A.set(D++,u)}if(b.events){b=b.events;h=[];for(let p of b)if(D=(p.tStartMs||0)+W,u=p.dDurationMs||0,p.id)U=String(p.id),b=TSw(this,p,D,u,U),h.push(b),this.X.set(U,b);else{p.wWinId?U=p.wWinId.toString():(U="_"+jf++,b=TSw(this,p,D,u,U),h.push(b),this.X.set(U,b));
var K;b=h;var m=p;u===0&&(u=5E3);c=this.X.get(U);let K2=(I=!!m.aAppend)?6:5,mD=m.segs,qR=null;m.pPenId&&(qR=this.Z.get(m.pPenId));for(m=0;m<mD.length;m++){var F=mD[m],M=F.utf8;if(M){var t=F.tOffsetMs||0;let yy=null;F.pPenId&&(yy=this.Z.get(F.pPenId));if((c.params.z9!=null?c.params.z9:c.Z.length>1?1:0)===2&&I&&M==="\n")continue;F=null;var v=[];if(K=yy&&yy.d_===1)a:{K=mD;var R=m;if(R+3>=K.length||!K[R+1].pPenId||!K[R+2].pPenId||!K[R+3].pPenId){K=!1;break a}var e=K[R+1].pPenId;(e=this.Z.get(e))&&e.d_&&
e.d_===2?(e=K[R+2].pPenId,e=this.Z.get(e),!e||!e.d_||e.d_<3?K=!1:(e=K[R+3].pPenId,K=(e=this.Z.get(e))&&e.d_&&e.d_===2?!0:!1)):K=!1}if(K)t=mD[m+1].utf8,F=mD[m+3].utf8,K=mD[m+2].utf8,R=this.Z.get(mD[m+2].pPenId),M=yD2(M,t,K,F,R),F=new wx(D,u,K2,U,M,I,yy),m+=3;else{if(M.indexOf("<")>-1){v=yy;K=qR;R=D;e=u;var L=t,k=K2,S=I;let C2=[];var H=Rs(`<html>${M}</html>`);if(!H.getElementsByTagName("parsererror").length&&H.firstChild?.childNodes.length)for(let dZ of H.firstChild.childNodes){H=dZ.textContent?.replace(/\n/g,
"")??"";if(dZ.nodeType===3&&(!H||H.match(/^ *$/)!=null))continue;let LG={};Object.assign(LG,v||K);switch(dZ?.tagName){case "b":LG.bold=!0;break;case "i":LG.italic=!0;break;case "u":LG.underline=!0}C2.push(new wx(R+L,e-L,k,c.id,H,S,LG))}v=C2}v.length||(v=[new wx(D+t,u-t,K2,c.id,M,I,yy||qR)])}if(v.length)for(let C2 of v)b.push(C2),c.Z.push(C2);else F&&(b.push(F),c.Z.push(F))}I=!0}}W=h}else W=[];return W}};var UQR=class extends u1{constructor(b,W,c){super(b);this.videoData=W;this.audioTrack=c;this.U=W.CA}J(b,W,c){Cg2(this.videoData.videoId,b.vssId,c.CL)}Y(b){if(this.audioTrack)for(let W of this.audioTrack.captionTracks)v3(this.Z,W);b.FO()}};var vh1=class extends Uk{constructor(b,W,c,U,u,I,D,h,K,m){super(b,W,c,U,u,I,D,h,K,m);this.type=1}o1(b){var W=this.O.Z;super.o1(b);for(b=b.length;b<W.length;b++){let u=W[b],I;if(U&&u.Z===c)I=U;else{I={};Object.assign(I,u.Z);Object.assign(I,uyR);var c=u.Z;var U=I}MMZ(this,u,I)}}},uyR={Qs:!0};var JDg=class extends kFw{constructor(b,W){super();this.trackData=b;this.L=W;this.version=this.Y=this.O=this.byteOffset=0;this.X=[];this.Z=new DataView(this.trackData)}A(b,W,c,U,u){if(c<U){let I="_"+jf++;c=c/1E3-this.L;U=U/1E3-this.L;b=new E6(c,U-c,5,I,{textAlign:0,FE:0,pk:W*2.5,fW:b*5.33});u=new wx(c,U-c,5,I,u);this.X.push(b);this.X.push(u)}}},s5g=class extends Iy{constructor(b,W){super();this.X=b;this.A=W;this.track=this.A.languageName==="CC3"?4:0;this.Z=new eRv;this.Z.X=1<<this.track}O(b){b=new JDg(b,
this.X);if(BSC(b)){for(;b.byteOffset<b.Z.byteLength;)for(b.version===0?b.O=LX(b)*(1E3/45):b.version===1&&(b.O=LX(b)*4294967296+LX(b)),b.Y=kZ(b);b.Y>0;b.Y--){var W=kZ(b);let c=kZ(b),U=kZ(b);W&4&&(W&3)===this.track&&(this.track===0||this.track===1)&&(W=this.Z,W.Z.push({time:b.O,type:this.track,GX:c,rS:U,order:W.Z.length}))}AD$(this.Z,b);return b.X}return[]}reset(){this.Z.clear()}};var RRZ=class extends Uk{constructor(b,W,c,U,u,I,D,h,K,m){super(b,W,c,U,u,I,D,h,K,m);this.type=2;this.Nk=[];this.qk=this.O0=this.xv=0;this.yj=NaN;this.DB=0;this.uI=null;this.iT=new g.a2(this.hj,433,this);this.N&&(m.createClientVe(this.N,this,167342),this.Qj(this.N,"click",()=>{m.logClick(this.N)}),b=new g.X5(this.element,!0),g.B(this,b),b.subscribe("hoverstart",()=>{m.logVisibility(this.N,!0)},this));
g.EB(this.element,"ytp-caption-window-rollup");g.B(this,this.iT);g.KK(this.element,"overflow","hidden")}f3(){var b=this.iT;b.stop();b.CD()}hj(){this.element.removeEventListener("transitionend",this.hj,!1);g.ee(this.element,"ytp-rollup-mode");this.D(this.uI,!0)}gC(){return this.L?this.qk:this.O0}A$(){return this.L?this.O0:this.qk}D(b,W){this.uI=b;if(this.O.params.Uu){var c=0;for(let U=0;U<this.U.length&&c<b.length;U++)this.U[U]===b[c]&&c++;c>0&&c<b.length&&(b=this.U.concat(b.slice(c)));this.DB=this.qk;
this.O0=this.qk=0;super.D(b);VM2(this,W)}super.D(b)}};var I_w=class{constructor(b,W,c,U){this.K=b;this.Y=W;this.logger=c;this.Xo=U;this.EP=[];this.Z=null;this.O=[];this.uk=[];this.X=null;b=this.K.S().experiments.Z("html5_override_micro_discontinuities_threshold_ms");this.A=b>0?b:10}unload(){this.X!=null&&(this.K.removeEventListener("sabrCaptionsDataLoaded",this.X),this.X=null);this.EP=[];this.Z=null;this.O=[];this.K.p9("sabrCaptionsBufferedRangesUpdated",this.EP)}J(b){return{formatId:g.m9(b.info.B.info,this.Xo),Yv:b.info.Yv+(this.Xo?0:1),startTimeMs:b.info.A*
1E3,durationMs:b.info.J*1E3}}};var DQm=class extends u1{constructor(b,W){super(W);this.X=b;this.K=W;this.logger=new g.pD("caps");this.N=this.zc=null;this.D=new I_w(this.K,this,this.logger,this.X.Xo)}J(b,W,c){this.O();W=b.getId();W=W!=null&&W in this.X.Z?this.X.Z[W]:null;W||(W=b.languageCode,W=this.X.isManifestless?rDv(this,W,"386"):rDv(this,W));W&&(this.N=b,this.zc=W,dxR(this.D,c),this.K.p9("sabrCaptionsTrackChanged",g.m9(W.info,this.X.Xo)))}Y(b){var W=this.X.isManifestless?peg(this,"386"):peg(this);for(let c of W)v3(this.Z,c);
b.FO()}O(){this.N&&(this.N=this.zc=null,this.D.unload(),this.K.p9("sabrCaptionsTrackChanged",null))}L(){return""}};var zMb="WEBVTT".split("").map(b=>b.charCodeAt(0)),Und=class extends Iy{constructor(){super()}O(b,W){b instanceof ArrayBuffer&&(b=g.vo(new Uint8Array(b)));
var c=[];b=b.split(hYv);for(let R=1;R<b.length;R++){var U=b[R],u=W;if(U!==""&&!KTR.test(U)){var I=DE.exec(U);if(I&&I.length>=4){var D=VM(I[1]),h=VM(I[2])-D;D+=u;var K=(I=I[3])?I.split(" "):[];I={};var m=null;var F="";var M=null,t="";for(let e of K){K=e.split(":");if(K.length!==2)continue;var v=K[1];switch(K[0]){case "line":K=v.split(",");K[0].endsWith("%")&&(m=K[0],I.fW=Number.parseInt(m,10),K.length===2&&(F=K[1].trim()));break;case "position":K=v.split(",");M=K[0];I.pk=Number.parseInt(M,10);K.length===
2&&(t=K[1].trim());break;case "align":switch(v){case "start":I.textAlign=0;break;case "middle":I.textAlign=2;break;case "end":I.textAlign=1}}}m||F||(F="end");if(!M)switch(I.textAlign){case 0:I.pk=0;break;case 1:I.pk=100;break;case 2:I.pk=50}if(I.textAlign!=null){m=0;switch(F){case "center":m+=3;break;case "end":m+=6;break;default:m+=0}switch(t){case "line-left":m+=0;break;case "center":m+=1;break;case "line-right":m+=2;break;default:switch(I.textAlign){case 0:m+=0;break;case 2:m+=1;break;case 1:m+=
2}}F=m<0||m>8?7:m;I.FE=F}U=U.substring(DE.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=I;I={};if(U.indexOf("<")<0&&U.indexOf("&")<0)u=bqg(D,h,5,t),D=new wx(D,h,5,u.id,U,!1,g.Fa(I)?void 0:I),c.push(u),c.push(D),u.Z.push(D);else for(F=U.split(Z0w),F.length===1?(U=5,t=bqg(D,h,U,t)):(m=U=6,t=Object.assign({dB:32},t),t=new E6(D,h,m,"_"+jf++,t)),c.push(t),m=D,M=0;M<F.length;M++)if(K=F[M],M%2===0){v=Rs(`<html>${K}</html>`);let e;v.getElementsByTagName("parsererror").length?(e=v.createElement("span"),
e.appendChild(v.createTextNode(K))):e=v.firstChild;WMv(this,m,h-(m-D),U,t,M>0,e,I,c)}else m=VM(K)+u}DE.lastIndex=0}}return c}},KTR=/^NOTE/,hYv=/(?:\r\n|\r|\n){2,}/,DE=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Z0w=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var Pmg=class extends g.SJ{constructor(b,W){super();this.K=b;this.G=W;this.Z=null;this.PZ=this.K.T7();this.logger=new g.pD("caps")}clear(){this.Z&&this.Z.dispose();this.Z=null}reset(){this.Z&&this.Z.reset()}Ax(){super.Ax();this.clear()}};var hRy={windowColor:"#080808",windowOpacity:0,textAlign:2,FE:7,pk:50,fW:100,isDefault:!0,Ha:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},Dnm={windowColor:"#080808",windowOpacity:0,textAlign:0,FE:7,pk:50,fW:100,isDefault:!0,Ha:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.Qo("captions",class extends g.xI{constructor(b){super(b);this.K=b;this.Nk=[];this.qk={};this.Vj={};this.N=!1;this.O="NONE";this.Z=this.U=this.D=this.Mk=this.vk=null;this.hj={FO:()=>{this.FO()},
CL:(U,u,I,D,h=0)=>{var K=Number(this.videoData.S().Tc().Z.jp(g.rIC)??0);h>0&&K>0&&this.videoData.lengthSeconds>0&&h/this.videoData.lengthSeconds>K?this.K.W("tts",{dropcap:h}):this.CL(U,u,I,D)}};
this.Wk=this.X=null;this.G=this.K.S();this.videoData=this.K.getVideoData();this.mx=this.K.WZ();this.Y={Ha:{}};this.L={Ha:{}};g.wC(this.videoData)?this.O="OFFLINE":g.y_Z(this.videoData,this.K)?this.O="HLS":CUb(this.videoData,this.K)?this.O="SABR_LIVE":g.wIC(this.videoData,this.K)?this.O="LIVE":this.videoData.captionTracks.length?this.O="INNERTUBE":this.videoData.j7&&(this.O="TTS");this.E0=this.G.controlsType==="3";this.xv=new Pmg(this.K,this.G);this.L9=new g.Bp(this);this.J=new g.IQ({V:"div",X_:"ytp-caption-window-container",
Jx:{id:"ytp-caption-window-container"}});this.O0={top:0,right:0,bottom:0,left:0,width:1,height:1};var W=null,c=g.XL("yt-html5-player-modules::subtitlesModuleData");c&&(W=new g.C$(c));this.storage=W;W=b.yz();this.Gn=!!W?.Vj();this.zn=!!W?.xv();this.A=Sf(this);this.zc=IBR(this);g.B(this,this.xv);this.A?this.bX=this.yj=null:(this.yj=new g.R2(this.j7,void 0,this),g.B(this,this.yj),this.bX=new g.a2(this.jQ,2E3,this),g.B(this,this.bX));g.B(this,this.L9);g.EW(this.player,this.J.element,4);g.B(this,this.J);
this.A||this.L9.Qj(b,"resize",this.o1);W=g.Dg(this.G)&&!g.R6()&&!this.K.isFullscreen();c=this.G.Tc().Z.jp(g.xC2)&&g.Az(this.G)&&g.ol;(this.VS=(W||c)&&!this.A&&!this.zc)&&this.L9.Qj(b,W?"resize":"fullscreentoggled",this.fu);this.L9.Qj(b,"onPlaybackAudioChange",this.HZ);this.L9.Qj(b,g.zA("captions"),U=>{this.onCueRangeEnter(U)});
this.L9.Qj(b,g.oE("captions"),U=>{this.onCueRangeExit(U)});
GY(this,A8()||{});g.gg(this.player,"onCaptionsModuleAvailable");this.O==="HLS"&&this.A&&(b=this.K.yz().Pr(),this.zn&&this.L9.Qj(b.textTracks,"addtrack",this.gC))}Ax(){if(this.A||this.zc){let b=this.K.yz();b&&!b.I1()&&b.U()}else nX(this,!1);super.Ax()}aB(){if(this.E0)return this.A||this.zc;if(this.O==="HLS")return this.A;var b=this.getAudioTrack();if(mnd(this)){if(!b.captionTracks.length)return!1;if(!this.Z)return!0}b=t8(b,g.q_(this.G));return b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?
rx(this):CX(this)||rx(this)?!0:Yv2(this)}load(){super.load();this.U=this.getAudioTrack();if(this.Z)this.X&&(this.xv.clear(),this.A?FMw(this,!0):this.player.getPresentingPlayerType()!==3&&this.Z.J(this.X,"json3",this.hj),this.O!=="HLS"&&this.A||this.zc||pX(this)||g.gg(this.player,"captionschanged",XX(this.X)));else{if(this.O==="OFFLINE")var b=new UQR(this.player,this.videoData,this.getAudioTrack());else this.O==="SABR_LIVE"?b=new DQm(this.videoData.Z,this.player):this.O==="HLS"?b=new fBg(this.player):
this.O==="LIVE"?b=new wib(this.videoData.Z,this.player):this.O==="INNERTUBE"?b=new Oq2(this.player,this.videoData,this.getAudioTrack()):(b=this.videoData,b=new jZy(this.player,this.videoData.j7,this.videoData.videoId,b.captionsLanguagePreference||b.n9.captionsLanguagePreference||g.lB(b,"yt:cc_default_lang")||b.n9.j7,this.videoData.tI,this.videoData.eventId));this.Z=b;g.B(this,this.Z);this.Z.Y(this.hj)}}unload(){this.A&&this.X?FMw(this,!1):(this.bX&&this.bX.P4(),this.player.In("captions"),this.Nk=
[],this.Z&&this.Z.O(),this.xv.clear(),this.D&&this.player.A4(this.D),this.o1());super.unload();this.player.qC();g.gg(this.player,"captionschanged",{})}create(){this.aB()&&this.load();var b;a:{if(this.G.j("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(b=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let W of b)if(W.kind==="asr"&&W.languageCode==="en"){b=
!0;break a}b=!1}b&&this.K.p9("showpromotooltip",this.J.element)}FO(){var b=t8(this.player.getAudioTrack(),g.q_(this.G));b=b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?os(this,this.N):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&rx(this)?zY(this):CX(this)||this.N||Yv2(this)?os(this,this.N):rx(this)?zY(this):null;this.O!=="HLS"&&this.A||this.zc?ghv(this,b):(!this.X&&b&&i1(this,b),g.gg(this.player,"onCaptionsTrackListChanged"),g.tw(this.player,"onApiChange"))}A$(){var b=this.K.yz().Pr().textTracks,W=null;
for(let c=0;c<b.length;c++)if(b[c].mode==="showing")a:{W=this.Z.Z.Z(!0);for(let U=0;U<W.length;U++)if(W[U].toString()===b[c].id){W=W[U];break a}W=null}(this.loaded?this.X:null)!==W&&i1(this,W,!0)}gC(){this.Z?.Y(this.hj)}I5(){!this.X&&this.A||this.unload()}CL(b,W,c,U){if(b){c2(this,this.X??void 0);this.Z.L9()&&(this.Nk=[],this.K.In("captions"),gx(this.yj),this.xv.reset());a:{var u=this.xv;U=U||0;c=iq2(u,b,c||0);b=[];try{for(let k of c){let S=k.trackData,H=k.Sf,p=u.G.j("safari_live_drm_captions_fix");
if(typeof S!=="string"){c=b;var I=c.concat;if(p&&oBZ(S))var D=uS2(u,S,H);else{var h=u,K=W,m=S,F=H,M=U;if(!NSm(m))throw Error("Invalid binary caption track data");h.Z||(h.Z=new s5g(M,K));D=h.Z.O(m,F)}var t=I.call(c,D)}else{if(S.substring(0,6)==="WEBVTT")var v=b.concat(uS2(u,S,H));else{c=b;var R=c.concat;b:{K=u;h=W;if(S[0]==="{")try{K.Z||(K.Z=new Svv(sZ2(h)));var e=K.Z.O(S,H);break b}catch(qR){g.P7(qR);e=[];break b}let K2=Rs(S);if(!K2||!K2.firstChild){let qR=Error("Invalid caption track data");qR.params=
S;throw qR;}if(K2.firstChild.tagName==="timedtext"){if(Number(K2.firstChild.getAttribute("format"))===3){m=K2;K.Z||(K.Z=new LMw(sZ2(h)));e=K.Z.O(m,H);break b}let qR=Error("Unsupported subtitles format in web player (Format2)");qR.params=S;throw qR;}if(K2.firstChild.tagName==="transcript"){let qR=Error("Unsupported subtitles format in web player (Format1)");qR.params=S;throw qR;}let mD=Error("Invalid caption track data");mD.params=S;throw mD;}v=R.call(c,e)}t=v}b=t}var L=b;break a}catch(k){g.z9(u.logger,
187101178,`Captions parsing failed: ${k.message}. `);u.clear();L=[];break a}L=void 0}this.G.j("html5_sabr_live_support_subfragmented_captions")&&this.Z instanceof DQm&&(W=this.Z.D,u=[],L.length>0&&(u=L.slice(W.O.length)),W.O=!W.Z||W.Z.info.UB?[]:L,L=u);L.length>0&&(W=this.X,this.gf(W,!!W,pX(this)?"g":this.N?"m":"s"));this.player.A4(L,void 0,this.O==="LIVE"||this.O==="SABR_LIVE");!this.N||this.zc||pX(this)||g.tu(this.G)||g.M_(this.G)||g.hu(this.G)||this.G.N==="shortspage"||this.player.isInline()||
(this.bX.P4(),L=jhm({FE:0,pk:5,fW:5,Uu:2,textAlign:0,nj:0,lang:"en"}),this.Mk=[L],W=["Click "," for settings"],this.vk||(u=new g.zc({V:"svg",Jx:{height:"100%",version:"1.1",viewBox:"0 0 36 36",width:"100%"},hx:[{V:"path",Kp:!0,Jx:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.B(this,u),this.vk=u.element),u=L.end-L.start,(t=g.oM(this.X))&&this.Mk.push(new wx(L.start,u,0,L.id,t)),this.Mk.push(new wx(L.start,u,0,L.id,W[0]),new wx(L.start,u,0,L.id,this.vk,!0),new wx(L.start,u,0,L.id,W[1],!0)),this.player.A4(this.Mk),g.f$(this.bX));!this.N||this.zc||pX(this)||(this.G.j("enable_player_captions_persistence_state_machine")?dx(this,!0):g.q_(this.G)?b1(this,!0):W2(this,!0),this.U&&(this.U.A=this.X),this.player.qC());this.N=!1}}onCueRangeEnter(b){this.Nk.push(b);
gx(this.yj)}onCueRangeExit(b){g.H6(this.Nk,b);this.Z instanceof wib&&this.Z.zc&&this.player.Bn([b]);gx(this.yj)}getCaptionWindowContainerId(){return this.J.element.id}jQ(){KMw(this,this.Mk);this.Mk=null}j7(){if(!this.VS||!this.A){this.yj.stop();g.Mg(this.Vj);this.Nk.sort(g.pM);var b=this.Nk;if(this.D){let W=g.lC(b,function(c){return this.D.indexOf(c)===-1},this);
W.length&&(b=W)}for(let W of b)W instanceof E6?t1g(this,W):xny(this,W);for(let [W,c]of Object.entries(this.qk)){let U=W,u=c;this.Vj[U]?(u.element.parentNode||(u instanceof RRZ||u instanceof vh1||g.ui(this.qk,(I,D)=>{D!==U&&I.O.params.FE===u.O.params.FE&&I.O.params.pk===u.O.params.pk&&I.O.params.fW===u.O.params.fW&&(I.dispose(),delete this.qk[D]);return D===U},this),this.J.element.appendChild(u.element)),u.D(this.Vj[U])):(u.dispose(),delete this.qk[U])}}}Fb(){GY(this,{},!0);
g.gg(this.player,"captionssettingschanged")}lw(){var b=this.G.j("enable_player_captions_new_style_defaults")?Dnm:hRy,W=b.Ha;b={background:W.background,backgroundOpacity:W.backgroundOpacity,charEdgeStyle:W.charEdgeStyle,color:W.color,fontFamily:W.fontFamily,fontSizeIncrement:W.fontSizeIncrement,fontStyle:W.bold&&W.italic?3:W.bold?1:W.italic?2:0,textOpacity:W.textOpacity,windowColor:b.windowColor,windowOpacity:b.windowOpacity};W=A8()||{};W.background!=null&&(b.background=W.background);W.backgroundOverride!=
null&&(b.backgroundOverride=W.backgroundOverride);W.backgroundOpacity!=null&&(b.backgroundOpacity=W.backgroundOpacity);W.backgroundOpacityOverride!=null&&(b.backgroundOpacityOverride=W.backgroundOpacityOverride);W.charEdgeStyle!=null&&(b.charEdgeStyle=W.charEdgeStyle);W.charEdgeStyleOverride!=null&&(b.charEdgeStyleOverride=W.charEdgeStyleOverride);W.color!=null&&(b.color=W.color);W.colorOverride!=null&&(b.colorOverride=W.colorOverride);W.fontFamily!=null&&(b.fontFamily=W.fontFamily);W.fontFamilyOverride!=
null&&(b.fontFamilyOverride=W.fontFamilyOverride);W.fontSizeIncrement!=null&&(b.fontSizeIncrement=W.fontSizeIncrement);W.fontSizeIncrementOverride!=null&&(b.fontSizeIncrementOverride=W.fontSizeIncrementOverride);W.fontStyle!=null&&(b.fontStyle=W.fontStyle);W.fontStyleOverride!=null&&(b.fontStyleOverride=W.fontStyleOverride);W.textOpacity!=null&&(b.textOpacity=W.textOpacity);W.textOpacityOverride!=null&&(b.textOpacityOverride=W.textOpacityOverride);W.windowColor!=null&&(b.windowColor=W.windowColor);
W.windowColorOverride!=null&&(b.windowColorOverride=W.windowColorOverride);W.windowOpacity!=null&&(b.windowOpacity=W.windowOpacity);W.windowOpacityOverride!=null&&(b.windowOpacityOverride=W.windowOpacityOverride);return b}da(b,W){var c={};Object.assign(c,A8());Object.assign(c,b);GY(this,c,W);g.gg(this.player,"captionssettingschanged")}o1(){!this.A&&this.loaded&&(g.cX(this.qk,function(b,W){b.dispose();delete this.qk[W]},this),this.j7())}EG(b,W){switch(b){case "fontSize":if(isNaN(W))break;
b=g.CZ(W,-2,4);this.da({fontSizeIncrement:b});return b;case "reload":W&&!this.A&&i1(this,this.X,!0);break;case "stickyLoading":W!==void 0&&this.G.J&&(this.G.j("enable_player_captions_persistence_state_machine")?dx(this,!(!W||!W.userInitiated)):g.q_(this.G)?b1(this,!!W):W2(this,!!W));break;case "track":return qv$(this,W);case "tracklist":return this.Z?g.ew(this.Z.Z.Z(!(!W||!W.includeAsr)),c=>XX(c)):[];
case "translationLanguages":return this.Z?this.Z.U.map(c=>Object.assign({},c)):[];
case "sampleSubtitles":this.A||W===void 0||nX(this,!!W);break;case "sampleSubtitlesCustomized":this.A||nX(this,!!W,W);break;case "recommendedTranslationLanguages":return g.OX();case "defaultTranslationSourceTrackIndices":return this.Z?this.Z.O0:[]}}getOptions(){var b="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.G.J&&b.push("stickyLoading");return b}dP(){var b=this.X;if(this.K.kV("captions")){if(this.G.j("html5_modify_caption_vss_logging"))return(b=this.videoData.m2??
null)?{cc:g.WS(b)}:{};if(b){let W=b.vssId;b.translationLanguage&&W&&(W=`t${W}.${g.bL(b)}`);return{cc:W}}}return{}}Ro(b){this.isSubtitlesOn()?(this.G.j("enable_player_captions_persistence_state_machine")&&b?dx(this,!1):g.q_(this.G)?b1(this,!1):W2(this,!1),c2(this),i1(this,null,!0)):this.VG(b)}VG(b){var W=pX(this)||!this.X?os(this,!0):this.X;W&&this.D3(W.vssId,"m");this.isSubtitlesOn()||i1(this,W,this.G.j("enable_player_captions_persistence_state_machine")?b:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.X&&!pX(this)}HZ(){var b=pX(this);rx(this,b)?i1(this,this.getAudioTrack().Z,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),mnd(this)&&(this.N=!1,this.X=null,this.Z&&(this.Z.dispose(),this.Z=null)),this.aB()&&(b?i1(this,os(this,!1),!1):this.load()))}zE(b){if(this.G.experiments.Sp("web_enable_captions_set_target_container")&&b!==this.Wk){var W=this.J.element;W.parentNode&&g.ow(W);(this.Wk=b)?(this.Wk.appendChild(W),W.style.position="absolute",W.style.bottom="0",W.style.left=
"0",W.style.width="100%",W.style.height="auto",W.style.top="auto"):(g.EW(this.player,W,4),W.style.position="absolute",W.style.bottom="auto",W.style.left="0",W.style.width="100%",W.style.height="100%",W.style.top="0");this.o1()}}VZ(b){b&&(this.O0={top:b.top,right:b.right,bottom:b.bottom,left:b.left,width:1-b.left-b.right,height:1-b.top-b.bottom},this.J.element.style.top=`${this.O0.top*100}%`,this.J.element.style.left=`${this.O0.left*100}%`,this.J.element.style.width=`${this.O0.width*100}%`,this.J.element.style.height=
`${this.O0.height*100}%`,this.J.element.style.position="absolute",b=Atm(this))&&(this.J.element.style.width=`${b.width}px`,this.J.element.style.height=`${b.height}px`)}onVideoDataChange(b,W){b==="newdata"&&(this.videoData=W,this.loaded&&this.unload(),this.N=!1,this.X=null,this.Z&&(this.Z.dispose(),this.Z=null,g.gg(this.player,"captionschanged",{})),this.aB()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}fu(){if(this.G.Tc().Z.jp(g.xC2)){this.loaded&&this.unload();var b=this.K.yz();
b&&!b.I1()&&b.U();this.E0=this.K.isFullscreen()||this.G.controlsType==="3";this.A=Sf(this);this.zc=IBR(this);this.Z&&(this.A||this.zc)&&ghv(this,null)}else(b=this.K.yz())&&!b.I1()&&b.U(),this.K.isFullscreen()?(this.A=this.E0=!0,this.loaded&&this.FO()):(this.E0=this.G.controlsType==="3",this.A=Sf(this));i1(this,this.X)}nu(){var b=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;b&&g.Ml(this.player,"innertubeCommand",b)}gf(b,W,c){var U=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,
u="";b&&(u=b.vssId,u=u.replace(U,""));var I="";b&&b.getId()&&(I=b.getId()||"");b&&b.getXtags()&&(b=b.getXtags(),b=b.replace(U,""),I=I.concat(`;${b}`));this.O==="HLS"&&(I="");this.K.gf(W?u:"",W?I:"",c)}D3(b,W){b=(b||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");b.length>0&&this.K.D3(b,W)}});})(_yt_player);
